version: '3'
services:
    web:
        build:
            context: .
            dockerfile: "Dockerfile"
        ports:
            - "8089:8089"
        environment:
            - QUEGG_ALLOW_UPLOADS=true
