#!/bin/sh
grep '<http://dbpedia.org/ontology/Building/floorArea>' ../resources/es//turtle/specific_mappingbased_properties_es.ttl>>../resources/es//property/dbo_Building/floorArea.ttl
grep '<http://dbpedia.org/ontology/MeanOfTransportation/height>' ../resources/es//turtle/specific_mappingbased_properties_es.ttl>>../resources/es//property/dbo_MeanOfTransportation/height.ttl
grep '<http://dbpedia.org/ontology/MeanOfTransportation/weight>' ../resources/es//turtle/specific_mappingbased_properties_es.ttl>>../resources/es//property/dbo_MeanOfTransportation/weight.ttl
grep '<http://dbpedia.org/ontology/Person/height>' ../resources/es//turtle/specific_mappingbased_properties_es.ttl>>../resources/es//property/dbo_Person/height.ttl
grep '<http://dbpedia.org/ontology/Planet/periapsis>' ../resources/es//turtle/specific_mappingbased_properties_es.ttl>>../resources/es//property/dbo_Planet/periapsis.ttl
grep '<http://dbpedia.org/ontology/PopulatedPlace/areaTotal>' ../resources/es//turtle/specific_mappingbased_properties_es.ttl>>../resources/es//property/dbo_PopulatedPlace/areaTotal.ttl
grep '<http://dbpedia.org/ontology/Weapon/height>' ../resources/es//turtle/specific_mappingbased_properties_es.ttl>>../resources/es//property/dbo_Weapon/height.ttl
grep '<http://dbpedia.org/ontology/Weapon/weight>' ../resources/es//turtle/specific_mappingbased_properties_es.ttl>>../resources/es//property/dbo_Weapon/weight.ttl
grep '<http://dbpedia.org/ontology/aSide>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_aSide.ttl
grep '<http://dbpedia.org/ontology/achievement>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_achievement.ttl
grep '<http://dbpedia.org/ontology/activeYearsStartDate>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_activeYearsStartDate.ttl
grep '<http://dbpedia.org/ontology/address>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_address.ttl
grep '<http://dbpedia.org/ontology/affiliation>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_affiliation.ttl
grep '<http://dbpedia.org/ontology/aircraftUser>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_aircraftUser.ttl
grep '<http://dbpedia.org/ontology/album>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_album.ttl
grep '<http://dbpedia.org/ontology/alliance>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_alliance.ttl
grep '<http://dbpedia.org/ontology/annualTemperature>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_annualTemperature.ttl
grep '<http://dbpedia.org/ontology/archipelago>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_archipelago.ttl
grep '<http://dbpedia.org/ontology/architecturalStyle>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_architecturalStyle.ttl
grep '<http://dbpedia.org/ontology/areaCode>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_areaCode.ttl
grep '<http://dbpedia.org/ontology/areaTotal>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_areaTotal.ttl
grep '<http://dbpedia.org/ontology/arm>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_arm.ttl
grep '<http://dbpedia.org/ontology/artist>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_artist.ttl
grep '<http://dbpedia.org/ontology/associate>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_associate.ttl
grep '<http://dbpedia.org/ontology/author>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_author.ttl
grep '<http://dbpedia.org/ontology/automobilePlatform>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_automobilePlatform.ttl
grep '<http://dbpedia.org/ontology/bSide>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_bSide.ttl
grep '<http://dbpedia.org/ontology/band>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_band.ttl
grep '<http://dbpedia.org/ontology/battle>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_battle.ttl
grep '<http://dbpedia.org/ontology/binomial>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_binomial.ttl
grep '<http://dbpedia.org/ontology/birthDate>' ../resources/es//turtle/persondata_es.ttl>>../resources/es//property/dbo_birthDate.ttl
grep '<http://dbpedia.org/ontology/birthPlace>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_birthPlace.ttl
grep '<http://dbpedia.org/ontology/broadcastArea>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_broadcastArea.ttl
grep '<http://dbpedia.org/ontology/broadcastRepeater>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_broadcastRepeater.ttl
grep '<http://dbpedia.org/ontology/broadcastTranslator>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_broadcastTranslator.ttl
grep '<http://dbpedia.org/ontology/builder>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_builder.ttl
grep '<http://dbpedia.org/ontology/buildingStartDate>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_buildingStartDate.ttl
grep '<http://dbpedia.org/ontology/callSign>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_callSign.ttl
grep '<http://dbpedia.org/ontology/capacity>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_capacity.ttl
grep '<http://dbpedia.org/ontology/careerPrizeMoney>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_careerPrizeMoney.ttl
grep '<http://dbpedia.org/ontology/category>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_category.ttl
grep '<http://dbpedia.org/ontology/censusYear>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_censusYear.ttl
grep '<http://dbpedia.org/ontology/chairman>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_chairman.ttl
grep '<http://dbpedia.org/ontology/chancellor>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_chancellor.ttl
grep '<http://dbpedia.org/ontology/characterInPlay>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_characterInPlay.ttl
grep '<http://dbpedia.org/ontology/child>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_child.ttl
grep '<http://dbpedia.org/ontology/cinematography>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_cinematography.ttl
grep '<http://dbpedia.org/ontology/citizenship>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_citizenship.ttl
grep '<http://dbpedia.org/ontology/class>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_class.ttl
grep '<http://dbpedia.org/ontology/closingDate>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_closingDate.ttl
grep '<http://dbpedia.org/ontology/club>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_club.ttl
grep '<http://dbpedia.org/ontology/cmykCoordinateCyanic>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_cmykCoordinateCyanic.ttl
grep '<http://dbpedia.org/ontology/cmykCoordinateYellow>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_cmykCoordinateYellow.ttl
grep '<http://dbpedia.org/ontology/coden>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_coden.ttl
grep '<http://dbpedia.org/ontology/colour>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_colour.ttl
grep '<http://dbpedia.org/ontology/combatant>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_combatant.ttl
grep '<http://dbpedia.org/ontology/committee>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_committee.ttl
grep '<http://dbpedia.org/ontology/commune>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_commune.ttl
grep '<http://dbpedia.org/ontology/compiler>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_compiler.ttl
grep '<http://dbpedia.org/ontology/computingInput>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_computingInput.ttl
grep '<http://dbpedia.org/ontology/computingPlatform>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_computingPlatform.ttl
grep '<http://dbpedia.org/ontology/conservationStatusSystem>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_conservationStatusSystem.ttl
grep '<http://dbpedia.org/ontology/constructionMaterial>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_constructionMaterial.ttl
grep '<http://dbpedia.org/ontology/country>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_country.ttl
grep '<http://dbpedia.org/ontology/coverArtist>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_coverArtist.ttl
grep '<http://dbpedia.org/ontology/creator>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_creator.ttl
grep '<http://dbpedia.org/ontology/curator>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_curator.ttl
grep '<http://dbpedia.org/ontology/currentProduction>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_currentProduction.ttl
grep '<http://dbpedia.org/ontology/dean>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_dean.ttl
grep '<http://dbpedia.org/ontology/deathDate>' ../resources/es//turtle/persondata_es.ttl>>../resources/es//property/dbo_deathDate.ttl
grep '<http://dbpedia.org/ontology/debutTeam>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_debutTeam.ttl
grep '<http://dbpedia.org/ontology/department>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_department.ttl
grep '<http://dbpedia.org/ontology/depth>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_depth.ttl
grep '<http://dbpedia.org/ontology/description>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_description.ttl
grep '<http://dbpedia.org/ontology/destination>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_destination.ttl
grep '<http://dbpedia.org/ontology/diameter>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_diameter.ttl
grep '<http://dbpedia.org/ontology/director>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_director.ttl
grep '<http://dbpedia.org/ontology/distance>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_distance.ttl
grep '<http://dbpedia.org/ontology/division>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_division.ttl
grep '<http://dbpedia.org/ontology/doctoralStudent>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_doctoralStudent.ttl
grep '<http://dbpedia.org/ontology/dorlandsPrefix>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_dorlandsPrefix.ttl
grep '<http://dbpedia.org/ontology/drainsFrom>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_drainsFrom.ttl
grep '<http://dbpedia.org/ontology/ecNumber>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_ecNumber.ttl
grep '<http://dbpedia.org/ontology/editor>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_editor.ttl
grep '<http://dbpedia.org/ontology/education>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_education.ttl
grep '<http://dbpedia.org/ontology/effectiveRadiatedPower>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_effectiveRadiatedPower.ttl
grep '<http://dbpedia.org/ontology/elevation>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_elevation.ttl
grep '<http://dbpedia.org/ontology/employer>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_employer.ttl
grep '<http://dbpedia.org/ontology/entrezgene>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_entrezgene.ttl
grep '<http://dbpedia.org/ontology/equity>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_equity.ttl
grep '<http://dbpedia.org/ontology/espnId>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_espnId.ttl
grep '<http://dbpedia.org/ontology/event>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_event.ttl
grep '<http://dbpedia.org/ontology/explorer>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_explorer.ttl
grep '<http://dbpedia.org/ontology/extinctionYear>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_extinctionYear.ttl
grep '<http://dbpedia.org/ontology/faaLocationIdentifier>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_faaLocationIdentifier.ttl
grep '<http://dbpedia.org/ontology/family>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_family.ttl
grep '<http://dbpedia.org/ontology/field>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_field.ttl
grep '<http://dbpedia.org/ontology/firstAppearance>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_firstAppearance.ttl
grep '<http://dbpedia.org/ontology/firstAscentYear>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_firstAscentYear.ttl
grep '<http://dbpedia.org/ontology/firstRace>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_firstRace.ttl
grep '<http://dbpedia.org/ontology/flag>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_flag.ttl
grep '<http://dbpedia.org/ontology/floorArea>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_floorArea.ttl
grep '<http://dbpedia.org/ontology/format>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_format.ttl
grep '<http://dbpedia.org/ontology/formationYear>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_formationYear.ttl
grep '<http://dbpedia.org/ontology/formerCallsign>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_formerCallsign.ttl
grep '<http://dbpedia.org/ontology/formerTeam>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_formerTeam.ttl
grep '<http://dbpedia.org/ontology/foundedBy>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_foundedBy.ttl
grep '<http://dbpedia.org/ontology/foundingDate>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_foundingDate.ttl
grep '<http://dbpedia.org/ontology/frequency>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_frequency.ttl
grep '<http://dbpedia.org/ontology/gameArtist>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_gameArtist.ttl
grep '<http://dbpedia.org/ontology/games>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_games.ttl
grep '<http://dbpedia.org/ontology/genre>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_genre.ttl
grep '<http://dbpedia.org/ontology/goldenGlobeAward>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_goldenGlobeAward.ttl
grep '<http://dbpedia.org/ontology/grammyAward>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_grammyAward.ttl
grep '<http://dbpedia.org/ontology/graySubject>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_graySubject.ttl
grep '<http://dbpedia.org/ontology/guest>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_guest.ttl
grep '<http://dbpedia.org/ontology/hasVariant>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_hasVariant.ttl
grep '<http://dbpedia.org/ontology/headquarter>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_headquarter.ttl
grep '<http://dbpedia.org/ontology/hgncid>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_hgncid.ttl
grep '<http://dbpedia.org/ontology/homeArena>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_homeArena.ttl
grep '<http://dbpedia.org/ontology/hometown>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_hometown.ttl
grep '<http://dbpedia.org/ontology/hsvCoordinateSaturation>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_hsvCoordinateSaturation.ttl
grep '<http://dbpedia.org/ontology/hubAirport>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_hubAirport.ttl
grep '<http://dbpedia.org/ontology/humanDevelopmentIndexRankingCategory>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_humanDevelopmentIndexRankingCategory.ttl
grep '<http://dbpedia.org/ontology/icaoLocationIdentifier>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_icaoLocationIdentifier.ttl
grep '<http://dbpedia.org/ontology/icd9>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_icd9.ttl
grep '<http://dbpedia.org/ontology/id>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_id.ttl
grep '<http://dbpedia.org/ontology/illustrator>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_illustrator.ttl
grep '<http://dbpedia.org/ontology/imdbId>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_imdbId.ttl
grep '<http://dbpedia.org/ontology/influenced>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_influenced.ttl
grep '<http://dbpedia.org/ontology/instrument>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_instrument.ttl
grep '<http://dbpedia.org/ontology/isHandicappedAccessible>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_isHandicappedAccessible.ttl
grep '<http://dbpedia.org/ontology/isbn>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_isbn.ttl
grep '<http://dbpedia.org/ontology/iso6392Code>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_iso6392Code.ttl
grep '<http://dbpedia.org/ontology/issn>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_issn.ttl
grep '<http://dbpedia.org/ontology/kingdom>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_kingdom.ttl
grep '<http://dbpedia.org/ontology/language>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_language.ttl
grep '<http://dbpedia.org/ontology/languageRegulator>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_languageRegulator.ttl
grep '<http://dbpedia.org/ontology/lastAppearance>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_lastAppearance.ttl
grep '<http://dbpedia.org/ontology/latestReleaseVersion>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_latestReleaseVersion.ttl
grep '<http://dbpedia.org/ontology/leader>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_leader.ttl
grep '<http://dbpedia.org/ontology/leaderTitle>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_leaderTitle.ttl
grep '<http://dbpedia.org/ontology/length>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_length.ttl
grep '<http://dbpedia.org/ontology/licensee>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_licensee.ttl
grep '<http://dbpedia.org/ontology/literaryGenre>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_literaryGenre.ttl
grep '<http://dbpedia.org/ontology/location>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_location.ttl
grep '<http://dbpedia.org/ontology/locationCountry>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_locationCountry.ttl
grep '<http://dbpedia.org/ontology/logo>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_logo.ttl
grep '<http://dbpedia.org/ontology/lyrics>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_lyrics.ttl
grep '<http://dbpedia.org/ontology/majorShrine>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_majorShrine.ttl
grep '<http://dbpedia.org/ontology/manager>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_manager.ttl
grep '<http://dbpedia.org/ontology/map>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_map.ttl
grep '<http://dbpedia.org/ontology/marketCapitalisation>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_marketCapitalisation.ttl
grep '<http://dbpedia.org/ontology/maximumElevation>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_maximumElevation.ttl
grep '<http://dbpedia.org/ontology/measurements>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_measurements.ttl
grep '<http://dbpedia.org/ontology/meshId>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_meshId.ttl
grep '<http://dbpedia.org/ontology/militaryBranch>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_militaryBranch.ttl
grep '<http://dbpedia.org/ontology/militaryRank>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_militaryRank.ttl
grep '<http://dbpedia.org/ontology/minimumElevation>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_minimumElevation.ttl
grep '<http://dbpedia.org/ontology/modelStartYear>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_modelStartYear.ttl
grep '<http://dbpedia.org/ontology/motto>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_motto.ttl
grep '<http://dbpedia.org/ontology/mouthPosition>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_mouthPosition.ttl
grep '<http://dbpedia.org/ontology/municipality>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_municipality.ttl
grep '<http://dbpedia.org/ontology/musicComposer>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_musicComposer.ttl
grep '<http://dbpedia.org/ontology/musicalBand>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_musicalBand.ttl
grep '<http://dbpedia.org/ontology/name>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_name.ttl
grep '<http://dbpedia.org/ontology/nationalTeam>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_nationalTeam.ttl
grep '<http://dbpedia.org/ontology/nationality>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_nationality.ttl
grep '<http://dbpedia.org/ontology/network>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_network.ttl
grep '<http://dbpedia.org/ontology/notableWork>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_notableWork.ttl
grep '<http://dbpedia.org/ontology/number>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_number.ttl
grep '<http://dbpedia.org/ontology/numberOfAcademicStaff>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfAcademicStaff.ttl
grep '<http://dbpedia.org/ontology/numberOfCompetitors>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfCompetitors.ttl
grep '<http://dbpedia.org/ontology/numberOfEmployees>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfEmployees.ttl
grep '<http://dbpedia.org/ontology/numberOfGoldMedalsWon>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfGoldMedalsWon.ttl
grep '<http://dbpedia.org/ontology/numberOfPages>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfPages.ttl
grep '<http://dbpedia.org/ontology/numberOfParticipatingNations>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfParticipatingNations.ttl
grep '<http://dbpedia.org/ontology/numberOfPlatformLevels>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfPlatformLevels.ttl
grep '<http://dbpedia.org/ontology/numberOfRooms>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfRooms.ttl
grep '<http://dbpedia.org/ontology/numberOfSilverMedalsWon>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfSilverMedalsWon.ttl
grep '<http://dbpedia.org/ontology/numberOfStaff>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfStaff.ttl
grep '<http://dbpedia.org/ontology/numberOfSuites>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfSuites.ttl
grep '<http://dbpedia.org/ontology/numberOfVisitors>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_numberOfVisitors.ttl
grep '<http://dbpedia.org/ontology/oclc>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_oclc.ttl
grep '<http://dbpedia.org/ontology/officerInCharge>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_officerInCharge.ttl
grep '<http://dbpedia.org/ontology/officialOpenedBy>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_officialOpenedBy.ttl
grep '<http://dbpedia.org/ontology/olympicOathSwornByAthlete>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_olympicOathSwornByAthlete.ttl
grep '<http://dbpedia.org/ontology/omim>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_omim.ttl
grep '<http://dbpedia.org/ontology/openingTheme>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_openingTheme.ttl
grep '<http://dbpedia.org/ontology/operatingIncome>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_operatingIncome.ttl
grep '<http://dbpedia.org/ontology/operator>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_operator.ttl
grep '<http://dbpedia.org/ontology/orderInOffice>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_orderInOffice.ttl
grep '<http://dbpedia.org/ontology/originalName>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_originalName.ttl
grep '<http://dbpedia.org/ontology/otherServingLines>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_otherServingLines.ttl
grep '<http://dbpedia.org/ontology/owningCompany>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_owningCompany.ttl
grep '<http://dbpedia.org/ontology/parent>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_parent.ttl
grep '<http://dbpedia.org/ontology/parish>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_parish.ttl
grep '<http://dbpedia.org/ontology/party>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_party.ttl
grep '<http://dbpedia.org/ontology/pdb>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_pdb.ttl
grep '<http://dbpedia.org/ontology/periapsis>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_periapsis.ttl
grep '<http://dbpedia.org/ontology/person>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_person.ttl
grep '<http://dbpedia.org/ontology/phylum>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_phylum.ttl
grep '<http://dbpedia.org/ontology/pictureDescription>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_pictureDescription.ttl
grep '<http://dbpedia.org/ontology/place>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_place.ttl
grep '<http://dbpedia.org/ontology/plays>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_plays.ttl
grep '<http://dbpedia.org/ontology/poles>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_poles.ttl
grep '<http://dbpedia.org/ontology/populationMetro>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_populationMetro.ttl
grep '<http://dbpedia.org/ontology/populationUrban>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_populationUrban.ttl
grep '<http://dbpedia.org/ontology/postalCode>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_postalCode.ttl
grep '<http://dbpedia.org/ontology/predecessor>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_predecessor.ttl
grep '<http://dbpedia.org/ontology/premiereYear>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_premiereYear.ttl
grep '<http://dbpedia.org/ontology/president>' ../resources/es//turtle/mappingbased_objects_disjoint_domain_es.ttl>>../resources/es//property/dbo_president.ttl
grep '<http://dbpedia.org/ontology/previousWork>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_previousWork.ttl
grep '<http://dbpedia.org/ontology/principal>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_principal.ttl
grep '<http://dbpedia.org/ontology/product>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_product.ttl
grep '<http://dbpedia.org/ontology/productionEndYear>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_productionEndYear.ttl
grep '<http://dbpedia.org/ontology/profession>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_profession.ttl
grep '<http://dbpedia.org/ontology/programmeFormat>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_programmeFormat.ttl
grep '<http://dbpedia.org/ontology/prominence>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_prominence.ttl
grep '<http://dbpedia.org/ontology/provost>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_provost.ttl
grep '<http://dbpedia.org/ontology/publicationDate>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_publicationDate.ttl
grep '<http://dbpedia.org/ontology/purpose>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_purpose.ttl
grep '<http://dbpedia.org/ontology/railwayPlatforms>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_railwayPlatforms.ttl
grep '<http://dbpedia.org/ontology/recordDate>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_recordDate.ttl
grep '<http://dbpedia.org/ontology/recordedIn>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_recordedIn.ttl
grep '<http://dbpedia.org/ontology/refseq>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_refseq.ttl
grep '<http://dbpedia.org/ontology/regionServed>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_regionServed.ttl
grep '<http://dbpedia.org/ontology/relation>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_relation.ttl
grep '<http://dbpedia.org/ontology/releaseDate>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_releaseDate.ttl
grep '<http://dbpedia.org/ontology/religiousHeadLabel>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_religiousHeadLabel.ttl
grep '<http://dbpedia.org/ontology/requirement>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_requirement.ttl
grep '<http://dbpedia.org/ontology/result>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_result.ttl
grep '<http://dbpedia.org/ontology/review>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_review.ttl
grep '<http://dbpedia.org/ontology/rgbCoordinateGreen>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_rgbCoordinateGreen.ttl
grep '<http://dbpedia.org/ontology/riverMouth>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_riverMouth.ttl
grep '<http://dbpedia.org/ontology/routeEnd>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_routeEnd.ttl
grep '<http://dbpedia.org/ontology/routeJunction>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_routeJunction.ttl
grep '<http://dbpedia.org/ontology/routeStart>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_routeStart.ttl
grep '<http://dbpedia.org/ontology/routeTypeAbbreviation>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_routeTypeAbbreviation.ttl
grep '<http://dbpedia.org/ontology/runwayDesignation>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_runwayDesignation.ttl
grep '<http://dbpedia.org/ontology/runwaySurface>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_runwaySurface.ttl
grep '<http://dbpedia.org/ontology/salary>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_salary.ttl
grep '<http://dbpedia.org/ontology/season>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_season.ttl
grep '<http://dbpedia.org/ontology/seatingCapacity>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_seatingCapacity.ttl
grep '<http://dbpedia.org/ontology/series>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_series.ttl
grep '<http://dbpedia.org/ontology/serviceEndYear>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_serviceEndYear.ttl
grep '<http://dbpedia.org/ontology/servingRailwayLine>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_servingRailwayLine.ttl
grep '<http://dbpedia.org/ontology/shareOfAudience>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_shareOfAudience.ttl
grep '<http://dbpedia.org/ontology/shipBeam>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_shipBeam.ttl
grep '<http://dbpedia.org/ontology/shipDraft>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_shipDraft.ttl
grep '<http://dbpedia.org/ontology/shoreLength>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_shoreLength.ttl
grep '<http://dbpedia.org/ontology/sisterStation>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_sisterStation.ttl
grep '<http://dbpedia.org/ontology/sourceConfluence>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_sourceConfluence.ttl
grep '<http://dbpedia.org/ontology/species>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_species.ttl
grep '<http://dbpedia.org/ontology/spike>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_spike.ttl
grep '<http://dbpedia.org/ontology/spokesperson>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_spokesperson.ttl
grep '<http://dbpedia.org/ontology/sportSpecialty>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_sportSpecialty.ttl
grep '<http://dbpedia.org/ontology/staff>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_staff.ttl
grep '<http://dbpedia.org/ontology/state>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_state.ttl
grep '<http://dbpedia.org/ontology/style>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_style.ttl
grep '<http://dbpedia.org/ontology/subsequentInfrastructure>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_subsequentInfrastructure.ttl
grep '<http://dbpedia.org/ontology/subsidiary>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_subsidiary.ttl
grep '<http://dbpedia.org/ontology/successor>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_successor.ttl
grep '<http://dbpedia.org/ontology/synonym>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_synonym.ttl
grep '<http://dbpedia.org/ontology/teachingStaff>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_teachingStaff.ttl
grep '<http://dbpedia.org/ontology/teamSize>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_teamSize.ttl
grep '<http://dbpedia.org/ontology/territory>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_territory.ttl
grep '<http://dbpedia.org/ontology/timeInSpace>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_timeInSpace.ttl
grep '<http://dbpedia.org/ontology/timeshiftChannel>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_timeshiftChannel.ttl
grep '<http://dbpedia.org/ontology/toll>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_toll.ttl
grep '<http://dbpedia.org/ontology/torchBearer>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_torchBearer.ttl
grep '<http://dbpedia.org/ontology/tradeMark>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_tradeMark.ttl
grep '<http://dbpedia.org/ontology/translator>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_translator.ttl
grep '<http://dbpedia.org/ontology/type>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_type.ttl
grep '<http://dbpedia.org/ontology/unitCost>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_unitCost.ttl
grep '<http://dbpedia.org/ontology/veneratedIn>' ../resources/es//turtle/mappingbased_objects_disjoint_range_es.ttl>>../resources/es//property/dbo_veneratedIn.ttl
grep '<http://dbpedia.org/ontology/vicePrincipal>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_vicePrincipal.ttl
grep '<http://dbpedia.org/ontology/voiceType>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_voiceType.ttl
grep '<http://dbpedia.org/ontology/webcast>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_webcast.ttl
grep '<http://dbpedia.org/ontology/width>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_width.ttl
grep '<http://dbpedia.org/ontology/wins>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_wins.ttl
grep '<http://dbpedia.org/ontology/year>' ../resources/es//turtle/mappingbased_literals_es.ttl>>../resources/es//property/dbo_year.ttl
