#!/bin/sh
grep '<http://dbpedia.org/ontology/activeYearsEndYear>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_activeYearsEndYear.ttl
grep '<http://dbpedia.org/ontology/address>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_address.ttl
grep '<http://dbpedia.org/ontology/album>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_album.ttl
grep '<http://dbpedia.org/ontology/alpsMainPart>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_alpsMainPart.ttl
grep '<http://dbpedia.org/ontology/alpsSection>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_alpsSection.ttl
grep '<http://dbpedia.org/ontology/alpsSubgroup>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_alpsSubgroup.ttl
grep '<http://dbpedia.org/ontology/alpsSupergroup>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_alpsSupergroup.ttl
grep '<http://dbpedia.org/ontology/anthem>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_anthem.ttl
grep '<http://dbpedia.org/ontology/area>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_area.ttl
grep '<http://dbpedia.org/ontology/areaTotalRanking>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_areaTotalRanking.ttl
grep '<http://dbpedia.org/ontology/artist>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_artist.ttl
grep '<http://dbpedia.org/ontology/associatedMusicalArtist>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_associatedMusicalArtist.ttl
grep '<http://dbpedia.org/ontology/autonomy>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_autonomy.ttl
grep '<http://dbpedia.org/ontology/binomial>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_binomial.ttl
grep '<http://dbpedia.org/ontology/birthDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_birthDate.ttl
grep '<http://dbpedia.org/ontology/birthYear>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_birthYear.ttl
grep '<http://dbpedia.org/ontology/builder>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_builder.ttl
grep '<http://dbpedia.org/ontology/buildingStartDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_buildingStartDate.ttl
grep '<http://dbpedia.org/ontology/careerStation>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_careerStation.ttl
grep '<http://dbpedia.org/ontology/category>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_category.ttl
grep '<http://dbpedia.org/ontology/chiefEditor>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_chiefEditor.ttl
grep '<http://dbpedia.org/ontology/cinematography>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_cinematography.ttl
grep '<http://dbpedia.org/ontology/citizenship>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_citizenship.ttl
grep '<http://dbpedia.org/ontology/classis>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_classis.ttl
grep '<http://dbpedia.org/ontology/club>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_club.ttl
grep '<http://dbpedia.org/ontology/colour>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_colour.ttl
grep '<http://dbpedia.org/ontology/completionDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_completionDate.ttl
grep '<http://dbpedia.org/ontology/conservationStatusSystem>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_conservationStatusSystem.ttl
grep '<http://dbpedia.org/ontology/costumeDesigner>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_costumeDesigner.ttl
grep '<http://dbpedia.org/ontology/coverArtist>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_coverArtist.ttl
grep '<http://dbpedia.org/ontology/currentStatus>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_currentStatus.ttl
grep '<http://dbpedia.org/ontology/dateOfBurial>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_dateOfBurial.ttl
grep '<http://dbpedia.org/ontology/deathDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_deathDate.ttl
grep '<http://dbpedia.org/ontology/deathYear>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_deathYear.ttl
grep '<http://dbpedia.org/ontology/demonym>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_demonym.ttl
grep '<http://dbpedia.org/ontology/description>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_description.ttl
grep '<http://dbpedia.org/ontology/diameter>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_diameter.ttl
grep '<http://dbpedia.org/ontology/dissolutionDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_dissolutionDate.ttl
grep '<http://dbpedia.org/ontology/division>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_division.ttl
grep '<http://dbpedia.org/ontology/dubber>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_dubber.ttl
grep '<http://dbpedia.org/ontology/ecNumber>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_ecNumber.ttl
grep '<http://dbpedia.org/ontology/electionDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_electionDate.ttl
grep '<http://dbpedia.org/ontology/endCareer>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_endCareer.ttl
grep '<http://dbpedia.org/ontology/entrezgene>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_entrezgene.ttl
grep '<http://dbpedia.org/ontology/ethnicity>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_ethnicity.ttl
grep '<http://dbpedia.org/ontology/extinctionDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_extinctionDate.ttl
grep '<http://dbpedia.org/ontology/family>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_family.ttl
grep '<http://dbpedia.org/ontology/filmAudioType>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_filmAudioType.ttl
grep '<http://dbpedia.org/ontology/firstAppearance>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_firstAppearance.ttl
grep '<http://dbpedia.org/ontology/firstAscentYear>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_firstAscentYear.ttl
grep '<http://dbpedia.org/ontology/flagLink>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_flagLink.ttl
grep '<http://dbpedia.org/ontology/format>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_format.ttl
grep '<http://dbpedia.org/ontology/formationYear>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_formationYear.ttl
grep '<http://dbpedia.org/ontology/formula>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_formula.ttl
grep '<http://dbpedia.org/ontology/foundedBy>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_foundedBy.ttl
grep '<http://dbpedia.org/ontology/foundingDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_foundingDate.ttl
grep '<http://dbpedia.org/ontology/garrison>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_garrison.ttl
grep '<http://dbpedia.org/ontology/genre>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_genre.ttl
grep '<http://dbpedia.org/ontology/grossDomesticProduct>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_grossDomesticProduct.ttl
grep '<http://dbpedia.org/ontology/headquarter>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_headquarter.ttl
grep '<http://dbpedia.org/ontology/heir>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_heir.ttl
grep '<http://dbpedia.org/ontology/id>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_id.ttl
grep '<http://dbpedia.org/ontology/imageSize>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_imageSize.ttl
grep '<http://dbpedia.org/ontology/industry>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_industry.ttl
grep '<http://dbpedia.org/ontology/iso31661Code>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_iso31661Code.ttl
grep '<http://dbpedia.org/ontology/issn>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_issn.ttl
grep '<http://dbpedia.org/ontology/kingdom>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_kingdom.ttl
grep '<http://dbpedia.org/ontology/language>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_language.ttl
grep '<http://dbpedia.org/ontology/leader>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_leader.ttl
grep '<http://dbpedia.org/ontology/leaderParty>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_leaderParty.ttl
grep '<http://dbpedia.org/ontology/legalForm>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_legalForm.ttl
grep '<http://dbpedia.org/ontology/literaryGenre>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_literaryGenre.ttl
grep '<http://dbpedia.org/ontology/location>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_location.ttl
grep '<http://dbpedia.org/ontology/locationCountry>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_locationCountry.ttl
grep '<http://dbpedia.org/ontology/longtype>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_longtype.ttl
grep '<http://dbpedia.org/ontology/map>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_map.ttl
grep '<http://dbpedia.org/ontology/material>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_material.ttl
grep '<http://dbpedia.org/ontology/militaryUnit>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_militaryUnit.ttl
grep '<http://dbpedia.org/ontology/motto>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_motto.ttl
grep '<http://dbpedia.org/ontology/musicComposer>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_musicComposer.ttl
grep '<http://dbpedia.org/ontology/nationalTeamYear>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_nationalTeamYear.ttl
grep '<http://dbpedia.org/ontology/nationality>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_nationality.ttl
grep '<http://dbpedia.org/ontology/notes>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_notes.ttl
grep '<http://dbpedia.org/ontology/numberOfLiveAlbums>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_numberOfLiveAlbums.ttl
grep '<http://dbpedia.org/ontology/numberOfPlayers>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_numberOfPlayers.ttl
grep '<http://dbpedia.org/ontology/numberOfStateDeputies>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_numberOfStateDeputies.ttl
grep '<http://dbpedia.org/ontology/numberOfStudioAlbums>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_numberOfStudioAlbums.ttl
grep '<http://dbpedia.org/ontology/occupation>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_occupation.ttl
grep '<http://dbpedia.org/ontology/officialLanguage>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_officialLanguage.ttl
grep '<http://dbpedia.org/ontology/omim>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_omim.ttl
grep '<http://dbpedia.org/ontology/openingYear>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_openingYear.ttl
grep '<http://dbpedia.org/ontology/order>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_order.ttl
grep '<http://dbpedia.org/ontology/originalLanguage>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_originalLanguage.ttl
grep '<http://dbpedia.org/ontology/owner>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_owner.ttl
grep '<http://dbpedia.org/ontology/painter>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_painter.ttl
grep '<http://dbpedia.org/ontology/parentOrganisation>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_parentOrganisation.ttl
grep '<http://dbpedia.org/ontology/passengersPerDay>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_passengersPerDay.ttl
grep '<http://dbpedia.org/ontology/patron>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_patron.ttl
grep '<http://dbpedia.org/ontology/perCapitaIncome>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_perCapitaIncome.ttl
grep '<http://dbpedia.org/ontology/period>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_period.ttl
grep '<http://dbpedia.org/ontology/playRole>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_playRole.ttl
grep '<http://dbpedia.org/ontology/populationTotal>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_populationTotal.ttl
grep '<http://dbpedia.org/ontology/position>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_position.ttl
grep '<http://dbpedia.org/ontology/predecessor>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_predecessor.ttl
grep '<http://dbpedia.org/ontology/previousWork>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_previousWork.ttl
grep '<http://dbpedia.org/ontology/product>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_product.ttl
grep '<http://dbpedia.org/ontology/productionStartDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_productionStartDate.ttl
grep '<http://dbpedia.org/ontology/profession>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_profession.ttl
grep '<http://dbpedia.org/ontology/publicationDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_publicationDate.ttl
grep '<http://dbpedia.org/ontology/railwayPlatforms>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_railwayPlatforms.ttl
grep '<http://dbpedia.org/ontology/recordLabel>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_recordLabel.ttl
grep '<http://dbpedia.org/ontology/rector>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_rector.ttl
grep '<http://dbpedia.org/ontology/regionLink>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_regionLink.ttl
grep '<http://dbpedia.org/ontology/releaseDate>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_releaseDate.ttl
grep '<http://dbpedia.org/ontology/residence>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_residence.ttl
grep '<http://dbpedia.org/ontology/retired>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_retired.ttl
grep '<http://dbpedia.org/ontology/routeEndLocation>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_routeEndLocation.ttl
grep '<http://dbpedia.org/ontology/runtime>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_runtime.ttl
grep '<http://dbpedia.org/ontology/seatingCapacity>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_seatingCapacity.ttl
grep '<http://dbpedia.org/ontology/servingRailwayLine>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_servingRailwayLine.ttl
grep '<http://dbpedia.org/ontology/settingOfPlay>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_settingOfPlay.ttl
grep '<http://dbpedia.org/ontology/sex>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_sex.ttl
grep '<http://dbpedia.org/ontology/smiles>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_smiles.ttl
grep '<http://dbpedia.org/ontology/specialEffects>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_specialEffects.ttl
grep '<http://dbpedia.org/ontology/sport>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_sport.ttl
grep '<http://dbpedia.org/ontology/sportSpecialty>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_sportSpecialty.ttl
grep '<http://dbpedia.org/ontology/staff>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_staff.ttl
grep '<http://dbpedia.org/ontology/startCareer>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_startCareer.ttl
grep '<http://dbpedia.org/ontology/stateOfOrigin>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_stateOfOrigin.ttl
grep '<http://dbpedia.org/ontology/subsequentWork>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_subsequentWork.ttl
grep '<http://dbpedia.org/ontology/symbol>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_symbol.ttl
grep '<http://dbpedia.org/ontology/tenant>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_tenant.ttl
grep '<http://dbpedia.org/ontology/totalDiscs>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_totalDiscs.ttl
grep '<http://dbpedia.org/ontology/trackLength>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_trackLength.ttl
grep '<http://dbpedia.org/ontology/transmission>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_transmission.ttl
grep '<http://dbpedia.org/ontology/uniprot>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_uniprot.ttl
grep '<http://dbpedia.org/ontology/value>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_value.ttl
grep '<http://dbpedia.org/ontology/viceLeader>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_viceLeader.ttl
grep '<http://dbpedia.org/ontology/weight>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_weight.ttl
grep '<http://dbpedia.org/ontology/writer>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_writer.ttl
grep '<http://dbpedia.org/ontology/yearOfConstruction>' ../resources/it//turtle/*.ttl>>../resources/it//property/dbo_yearOfConstruction.ttl
