#!/bin/sh
grep '<http://dbpedia.org/ontology/absoluteMagnitude>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_absoluteMagnitude.ttl
grep '<http://dbpedia.org/ontology/acquirementDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_acquirementDate.ttl
grep '<http://dbpedia.org/ontology/activeYearsEndYear>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_activeYearsEndYear.ttl
grep '<http://dbpedia.org/ontology/activeYearsStartYear>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_activeYearsStartYear.ttl
grep '<http://dbpedia.org/ontology/administrativeCollectivity>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_administrativeCollectivity.ttl
grep '<http://dbpedia.org/ontology/administrativeHeadCity>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_administrativeHeadCity.ttl
grep '<http://dbpedia.org/ontology/agencyStationCode>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_agencyStationCode.ttl
grep '<http://dbpedia.org/ontology/aircraftBomber>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_aircraftBomber.ttl
grep '<http://dbpedia.org/ontology/aircraftFighter>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_aircraftFighter.ttl
grep '<http://dbpedia.org/ontology/album>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_album.ttl
grep '<http://dbpedia.org/ontology/alliance>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_alliance.ttl
grep '<http://dbpedia.org/ontology/alternativeTitle>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_alternativeTitle.ttl
grep '<http://dbpedia.org/ontology/anthem>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_anthem.ttl
grep '<http://dbpedia.org/ontology/appearancesInLeague>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_appearancesInLeague.ttl
grep '<http://dbpedia.org/ontology/archipelago>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_archipelago.ttl
grep '<http://dbpedia.org/ontology/architecturalStyle>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_architecturalStyle.ttl
grep '<http://dbpedia.org/ontology/areaCode>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_areaCode.ttl
grep '<http://dbpedia.org/ontology/areaOfCatchment>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_areaOfCatchment.ttl
grep '<http://dbpedia.org/ontology/areaQuote>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_areaQuote.ttl
grep '<http://dbpedia.org/ontology/areaUrban>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_areaUrban.ttl
grep '<http://dbpedia.org/ontology/arrondissement>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_arrondissement.ttl
grep '<http://dbpedia.org/ontology/assetUnderManagement>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_assetUnderManagement.ttl
grep '<http://dbpedia.org/ontology/associationOfLocalGovernment>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_associationOfLocalGovernment.ttl
grep '<http://dbpedia.org/ontology/atcSuffix>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_atcSuffix.ttl
grep '<http://dbpedia.org/ontology/athleticsDiscipline>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_athleticsDiscipline.ttl
grep '<http://dbpedia.org/ontology/authority>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_authority.ttl
grep '<http://dbpedia.org/ontology/averageSpeed>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_averageSpeed.ttl
grep '<http://dbpedia.org/ontology/awayColourHexCode>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_awayColourHexCode.ttl
grep '<http://dbpedia.org/ontology/barangays>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_barangays.ttl
grep '<http://dbpedia.org/ontology/battingSide>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_battingSide.ttl
grep '<http://dbpedia.org/ontology/battleHonours>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_battleHonours.ttl
grep '<http://dbpedia.org/ontology/birthDate>' ../resources/de//turtle/persondata_de.ttl>>../resources/de//property/dbo_birthDate.ttl
grep '<http://dbpedia.org/ontology/birthPlace>' ../resources/de//turtle/persondata_de.ttl>>../resources/de//property/dbo_birthPlace.ttl
grep '<http://dbpedia.org/ontology/boilingPoint>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_boilingPoint.ttl
grep '<http://dbpedia.org/ontology/breeder>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_breeder.ttl
grep '<http://dbpedia.org/ontology/broadcastNetwork>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_broadcastNetwork.ttl
grep '<http://dbpedia.org/ontology/buildingEndDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_buildingEndDate.ttl
grep '<http://dbpedia.org/ontology/buildingStartDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_buildingStartDate.ttl
grep '<http://dbpedia.org/ontology/callSign>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_callSign.ttl
grep '<http://dbpedia.org/ontology/capacity>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_capacity.ttl
grep '<http://dbpedia.org/ontology/careerPoints>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_careerPoints.ttl
grep '<http://dbpedia.org/ontology/casSupplemental>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_casSupplemental.ttl
grep '<http://dbpedia.org/ontology/causalties>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_causalties.ttl
grep '<http://dbpedia.org/ontology/ceo>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_ceo.ttl
grep '<http://dbpedia.org/ontology/champion>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_champion.ttl
grep '<http://dbpedia.org/ontology/characterInPlay>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_characterInPlay.ttl
grep '<http://dbpedia.org/ontology/chorusCharacterInPlay>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_chorusCharacterInPlay.ttl
grep '<http://dbpedia.org/ontology/circulation>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_circulation.ttl
grep '<http://dbpedia.org/ontology/cityRank>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_cityRank.ttl
grep '<http://dbpedia.org/ontology/class>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_class.ttl
grep '<http://dbpedia.org/ontology/closingDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_closingDate.ttl
grep '<http://dbpedia.org/ontology/club>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_club.ttl
grep '<http://dbpedia.org/ontology/cmpEvaDuration>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_cmpEvaDuration.ttl
grep '<http://dbpedia.org/ontology/coden>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_coden.ttl
grep '<http://dbpedia.org/ontology/colour>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_colour.ttl
grep '<http://dbpedia.org/ontology/combatant>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_combatant.ttl
grep '<http://dbpedia.org/ontology/commander>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_commander.ttl
grep '<http://dbpedia.org/ontology/commissioningDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_commissioningDate.ttl
grep '<http://dbpedia.org/ontology/completionDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_completionDate.ttl
grep '<http://dbpedia.org/ontology/computingMedia>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_computingMedia.ttl
grep '<http://dbpedia.org/ontology/constellation>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_constellation.ttl
grep '<http://dbpedia.org/ontology/constructionMaterial>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_constructionMaterial.ttl
grep '<http://dbpedia.org/ontology/continentRank>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_continentRank.ttl
grep '<http://dbpedia.org/ontology/country>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_country.ttl
grep '<http://dbpedia.org/ontology/county>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_county.ttl
grep '<http://dbpedia.org/ontology/creationYear>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_creationYear.ttl
grep '<http://dbpedia.org/ontology/crosses>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_crosses.ttl
grep '<http://dbpedia.org/ontology/currentlyUsedFor>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_currentlyUsedFor.ttl
grep '<http://dbpedia.org/ontology/damsire>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_damsire.ttl
grep '<http://dbpedia.org/ontology/dateOfAbandonment>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_dateOfAbandonment.ttl
grep '<http://dbpedia.org/ontology/deathPlace>' ../resources/de//turtle/persondata_de.ttl>>../resources/de//property/dbo_deathPlace.ttl
grep '<http://dbpedia.org/ontology/decommissioningDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_decommissioningDate.ttl
grep '<http://dbpedia.org/ontology/density>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_density.ttl
grep '<http://dbpedia.org/ontology/depictionDescription>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_depictionDescription.ttl
grep '<http://dbpedia.org/ontology/description>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_description.ttl
grep '<http://dbpedia.org/ontology/developer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_developer.ttl
grep '<http://dbpedia.org/ontology/director>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_director.ttl
grep '<http://dbpedia.org/ontology/discovered>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_discovered.ttl
grep '<http://dbpedia.org/ontology/dissolutionDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_dissolutionDate.ttl
grep '<http://dbpedia.org/ontology/dissolved>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_dissolved.ttl
grep '<http://dbpedia.org/ontology/district>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_district.ttl
grep '<http://dbpedia.org/ontology/draft>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_draft.ttl
grep '<http://dbpedia.org/ontology/draftRound>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_draftRound.ttl
grep '<http://dbpedia.org/ontology/draftYear>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_draftYear.ttl
grep '<http://dbpedia.org/ontology/editing>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_editing.ttl
grep '<http://dbpedia.org/ontology/elevation>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_elevation.ttl
grep '<http://dbpedia.org/ontology/elevatorCount>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_elevatorCount.ttl
grep '<http://dbpedia.org/ontology/endPoint>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_endPoint.ttl
grep '<http://dbpedia.org/ontology/engine>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_engine.ttl
grep '<http://dbpedia.org/ontology/engineType>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_engineType.ttl
grep '<http://dbpedia.org/ontology/epoch>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_epoch.ttl
grep '<http://dbpedia.org/ontology/escapeVelocity>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_escapeVelocity.ttl
grep '<http://dbpedia.org/ontology/explorer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_explorer.ttl
grep '<http://dbpedia.org/ontology/extinctionYear>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_extinctionYear.ttl
grep '<http://dbpedia.org/ontology/federalState>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_federalState.ttl
grep '<http://dbpedia.org/ontology/firstAirDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_firstAirDate.ttl
grep '<http://dbpedia.org/ontology/firstPublicationDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_firstPublicationDate.ttl
grep '<http://dbpedia.org/ontology/flag>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_flag.ttl
grep '<http://dbpedia.org/ontology/floorCount>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_floorCount.ttl
grep '<http://dbpedia.org/ontology/formationDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_formationDate.ttl
grep '<http://dbpedia.org/ontology/formerBandMember>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_formerBandMember.ttl
grep '<http://dbpedia.org/ontology/formerPartner>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_formerPartner.ttl
grep '<http://dbpedia.org/ontology/formula>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_formula.ttl
grep '<http://dbpedia.org/ontology/founder>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_founder.ttl
grep '<http://dbpedia.org/ontology/foundingYear>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_foundingYear.ttl
grep '<http://dbpedia.org/ontology/gameArtist>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_gameArtist.ttl
grep '<http://dbpedia.org/ontology/garrison>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_garrison.ttl
grep '<http://dbpedia.org/ontology/gnisCode>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_gnisCode.ttl
grep '<http://dbpedia.org/ontology/governmentType>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_governmentType.ttl
grep '<http://dbpedia.org/ontology/guest>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_guest.ttl
grep '<http://dbpedia.org/ontology/headquarter>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_headquarter.ttl
grep '<http://dbpedia.org/ontology/highestMountain>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_highestMountain.ttl
grep '<http://dbpedia.org/ontology/homeColourHexCode>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_homeColourHexCode.ttl
grep '<http://dbpedia.org/ontology/homeport>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_homeport.ttl
grep '<http://dbpedia.org/ontology/hubAirport>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_hubAirport.ttl
grep '<http://dbpedia.org/ontology/icaoLocationIdentifier>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_icaoLocationIdentifier.ttl
grep '<http://dbpedia.org/ontology/id>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_id.ttl
grep '<http://dbpedia.org/ontology/imageSize>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_imageSize.ttl
grep '<http://dbpedia.org/ontology/industry>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_industry.ttl
grep '<http://dbpedia.org/ontology/influenced>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_influenced.ttl
grep '<http://dbpedia.org/ontology/inseeCode>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_inseeCode.ttl
grep '<http://dbpedia.org/ontology/intercommunality>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_intercommunality.ttl
grep '<http://dbpedia.org/ontology/isPartOfMilitaryConflict>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_isPartOfMilitaryConflict.ttl
grep '<http://dbpedia.org/ontology/isil>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_isil.ttl
grep '<http://dbpedia.org/ontology/iso31661Code>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_iso31661Code.ttl
grep '<http://dbpedia.org/ontology/iso6392Code>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_iso6392Code.ttl
grep '<http://dbpedia.org/ontology/isoCode>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_isoCode.ttl
grep '<http://dbpedia.org/ontology/issn>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_issn.ttl
grep '<http://dbpedia.org/ontology/jockey>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_jockey.ttl
grep '<http://dbpedia.org/ontology/keyPerson>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_keyPerson.ttl
grep '<http://dbpedia.org/ontology/language>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_language.ttl
grep '<http://dbpedia.org/ontology/largestCity>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_largestCity.ttl
grep '<http://dbpedia.org/ontology/lastAirDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_lastAirDate.ttl
grep '<http://dbpedia.org/ontology/latestPreviewDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_latestPreviewDate.ttl
grep '<http://dbpedia.org/ontology/latestReleaseDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_latestReleaseDate.ttl
grep '<http://dbpedia.org/ontology/launchSite>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_launchSite.ttl
grep '<http://dbpedia.org/ontology/layingDown>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_layingDown.ttl
grep '<http://dbpedia.org/ontology/leader>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_leader.ttl
grep '<http://dbpedia.org/ontology/leaderParty>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_leaderParty.ttl
grep '<http://dbpedia.org/ontology/league>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_league.ttl
grep '<http://dbpedia.org/ontology/legislativePeriodName>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_legislativePeriodName.ttl
grep '<http://dbpedia.org/ontology/lengthQuote>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_lengthQuote.ttl
grep '<http://dbpedia.org/ontology/lieutenancyArea>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_lieutenancyArea.ttl
grep '<http://dbpedia.org/ontology/loadLimit>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_loadLimit.ttl
grep '<http://dbpedia.org/ontology/location>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_location.ttl
grep '<http://dbpedia.org/ontology/locationCountry>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_locationCountry.ttl
grep '<http://dbpedia.org/ontology/lunarEvaTime>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_lunarEvaTime.ttl
grep '<http://dbpedia.org/ontology/lunarModule>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_lunarModule.ttl
grep '<http://dbpedia.org/ontology/lunarSurfaceTime>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_lunarSurfaceTime.ttl
grep '<http://dbpedia.org/ontology/mainspan>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_mainspan.ttl
grep '<http://dbpedia.org/ontology/majorIsland>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_majorIsland.ttl
grep '<http://dbpedia.org/ontology/managerClub>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_managerClub.ttl
grep '<http://dbpedia.org/ontology/map>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_map.ttl
grep '<http://dbpedia.org/ontology/march>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_march.ttl
grep '<http://dbpedia.org/ontology/maximumDepth>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_maximumDepth.ttl
grep '<http://dbpedia.org/ontology/maximumDischarge>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_maximumDischarge.ttl
grep '<http://dbpedia.org/ontology/mayor>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_mayor.ttl
grep '<http://dbpedia.org/ontology/meltingPoint>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_meltingPoint.ttl
grep '<http://dbpedia.org/ontology/metropolitanBorough>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_metropolitanBorough.ttl
grep '<http://dbpedia.org/ontology/minimumDischarge>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_minimumDischarge.ttl
grep '<http://dbpedia.org/ontology/mission>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_mission.ttl
grep '<http://dbpedia.org/ontology/model>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_model.ttl
grep '<http://dbpedia.org/ontology/modelLineVehicle>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_modelLineVehicle.ttl
grep '<http://dbpedia.org/ontology/motto>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_motto.ttl
grep '<http://dbpedia.org/ontology/municipality>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_municipality.ttl
grep '<http://dbpedia.org/ontology/musicBy>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_musicBy.ttl
grep '<http://dbpedia.org/ontology/musicFormat>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_musicFormat.ttl
grep '<http://dbpedia.org/ontology/musicalArtist>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_musicalArtist.ttl
grep '<http://dbpedia.org/ontology/namedAfter>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_namedAfter.ttl
grep '<http://dbpedia.org/ontology/nationalYears>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_nationalYears.ttl
grep '<http://dbpedia.org/ontology/ndlId>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_ndlId.ttl
grep '<http://dbpedia.org/ontology/neighboringMunicipality>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_neighboringMunicipality.ttl
grep '<http://dbpedia.org/ontology/nextMission>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_nextMission.ttl
grep '<http://dbpedia.org/ontology/notableFeatures>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_notableFeatures.ttl
grep '<http://dbpedia.org/ontology/number>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_number.ttl
grep '<http://dbpedia.org/ontology/numberOfCrew>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_numberOfCrew.ttl
grep '<http://dbpedia.org/ontology/numberOfEpisodes>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_numberOfEpisodes.ttl
grep '<http://dbpedia.org/ontology/numberOfLines>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_numberOfLines.ttl
grep '<http://dbpedia.org/ontology/numberOfOrbits>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_numberOfOrbits.ttl
grep '<http://dbpedia.org/ontology/numberOfSeasons>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_numberOfSeasons.ttl
grep '<http://dbpedia.org/ontology/numberOfSpeakers>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_numberOfSpeakers.ttl
grep '<http://dbpedia.org/ontology/numberOfStations>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_numberOfStations.ttl
grep '<http://dbpedia.org/ontology/numberOfSuites>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_numberOfSuites.ttl
grep '<http://dbpedia.org/ontology/numberOfVehicles>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_numberOfVehicles.ttl
grep '<http://dbpedia.org/ontology/numberOfVolunteers>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_numberOfVolunteers.ttl
grep '<http://dbpedia.org/ontology/office>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_office.ttl
grep '<http://dbpedia.org/ontology/officialOpenedBy>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_officialOpenedBy.ttl
grep '<http://dbpedia.org/ontology/openingDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_openingDate.ttl
grep '<http://dbpedia.org/ontology/openingYear>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_openingYear.ttl
grep '<http://dbpedia.org/ontology/operator>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_operator.ttl
grep '<http://dbpedia.org/ontology/orderDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_orderDate.ttl
grep '<http://dbpedia.org/ontology/originalLanguage>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_originalLanguage.ttl
grep '<http://dbpedia.org/ontology/outflow>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_outflow.ttl
grep '<http://dbpedia.org/ontology/parentCompany>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_parentCompany.ttl
grep '<http://dbpedia.org/ontology/parish>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_parish.ttl
grep '<http://dbpedia.org/ontology/passengersPerDay>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_passengersPerDay.ttl
grep '<http://dbpedia.org/ontology/periapsis>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_periapsis.ttl
grep '<http://dbpedia.org/ontology/picture>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_picture.ttl
grep '<http://dbpedia.org/ontology/pictureFormat>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_pictureFormat.ttl
grep '<http://dbpedia.org/ontology/playingTime>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_playingTime.ttl
grep '<http://dbpedia.org/ontology/podiums>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_podiums.ttl
grep '<http://dbpedia.org/ontology/populationAsOf>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_populationAsOf.ttl
grep '<http://dbpedia.org/ontology/populationMetro>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_populationMetro.ttl
grep '<http://dbpedia.org/ontology/populationUrban>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_populationUrban.ttl
grep '<http://dbpedia.org/ontology/postalCode>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_postalCode.ttl
grep '<http://dbpedia.org/ontology/premiereDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_premiereDate.ttl
grep '<http://dbpedia.org/ontology/premiereYear>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_premiereYear.ttl
grep '<http://dbpedia.org/ontology/president>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_president.ttl
grep '<http://dbpedia.org/ontology/previousWork>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_previousWork.ttl
grep '<http://dbpedia.org/ontology/product>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_product.ttl
grep '<http://dbpedia.org/ontology/productionEndYear>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_productionEndYear.ttl
grep '<http://dbpedia.org/ontology/profession>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_profession.ttl
grep '<http://dbpedia.org/ontology/programmingLanguage>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_programmingLanguage.ttl
grep '<http://dbpedia.org/ontology/province>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_province.ttl
grep '<http://dbpedia.org/ontology/publisher>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_publisher.ttl
grep '<http://dbpedia.org/ontology/race>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_race.ttl
grep '<http://dbpedia.org/ontology/rank>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_rank.ttl
grep '<http://dbpedia.org/ontology/recordDate>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_recordDate.ttl
grep '<http://dbpedia.org/ontology/region>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_region.ttl
grep '<http://dbpedia.org/ontology/relatedMeanOfTransportation>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_relatedMeanOfTransportation.ttl
grep '<http://dbpedia.org/ontology/religion>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_religion.ttl
grep '<http://dbpedia.org/ontology/retired>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_retired.ttl
grep '<http://dbpedia.org/ontology/rightTributary>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_rightTributary.ttl
grep '<http://dbpedia.org/ontology/riverBranchOf>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_riverBranchOf.ttl
grep '<http://dbpedia.org/ontology/roofHeight>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_roofHeight.ttl
grep '<http://dbpedia.org/ontology/routeEnd>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_routeEnd.ttl
grep '<http://dbpedia.org/ontology/routeStart>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_routeStart.ttl
grep '<http://dbpedia.org/ontology/runtime>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_runtime.ttl
grep '<http://dbpedia.org/ontology/runwayLength>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_runwayLength.ttl
grep '<http://dbpedia.org/ontology/runwayWidth>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_runwayWidth.ttl
grep '<http://dbpedia.org/ontology/scientificName>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_scientificName.ttl
grep '<http://dbpedia.org/ontology/seasonNumber>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_seasonNumber.ttl
grep '<http://dbpedia.org/ontology/secondCommander>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_secondCommander.ttl
grep '<http://dbpedia.org/ontology/secretaryGeneral>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_secretaryGeneral.ttl
grep '<http://dbpedia.org/ontology/series>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_series.ttl
grep '<http://dbpedia.org/ontology/settingOfPlay>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_settingOfPlay.ttl
grep '<http://dbpedia.org/ontology/sex>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_sex.ttl
grep '<http://dbpedia.org/ontology/shoots>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_shoots.ttl
grep '<http://dbpedia.org/ontology/sire>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_sire.ttl
grep '<http://dbpedia.org/ontology/soccerTournamentTopScorer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_soccerTournamentTopScorer.ttl
grep '<http://dbpedia.org/ontology/space>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_space.ttl
grep '<http://dbpedia.org/ontology/spacestation>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_spacestation.ttl
grep '<http://dbpedia.org/ontology/sport>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_sport.ttl
grep '<http://dbpedia.org/ontology/starring>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_starring.ttl
grep '<http://dbpedia.org/ontology/startPoint>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_startPoint.ttl
grep '<http://dbpedia.org/ontology/stationVisitDuration>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_stationVisitDuration.ttl
grep '<http://dbpedia.org/ontology/strength>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_strength.ttl
grep '<http://dbpedia.org/ontology/subsequentWork>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_subsequentWork.ttl
grep '<http://dbpedia.org/ontology/superintendent>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_superintendent.ttl
grep '<http://dbpedia.org/ontology/systemRequirements>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_systemRequirements.ttl
grep '<http://dbpedia.org/ontology/team>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_team.ttl
grep '<http://dbpedia.org/ontology/temperature>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_temperature.ttl
grep '<http://dbpedia.org/ontology/territory>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_territory.ttl
grep '<http://dbpedia.org/ontology/throwingSide>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_throwingSide.ttl
grep '<http://dbpedia.org/ontology/thumbnailCaption>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_thumbnailCaption.ttl
grep '<http://dbpedia.org/ontology/timeZone>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_timeZone.ttl
grep '<http://dbpedia.org/ontology/toll>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_toll.ttl
grep '<http://dbpedia.org/ontology/topLevelDomain>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_topLevelDomain.ttl
grep '<http://dbpedia.org/ontology/torchBearer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_torchBearer.ttl
grep '<http://dbpedia.org/ontology/trackLength>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_trackLength.ttl
grep '<http://dbpedia.org/ontology/trainerClub>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_trainerClub.ttl
grep '<http://dbpedia.org/ontology/translator>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_translator.ttl
grep '<http://dbpedia.org/ontology/unitaryAuthority>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_unitaryAuthority.ttl
grep '<http://dbpedia.org/ontology/usk>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_usk.ttl
grep '<http://dbpedia.org/ontology/vehiclesPerDay>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_vehiclesPerDay.ttl
grep '<http://dbpedia.org/ontology/viafId>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_viafId.ttl
grep '<http://dbpedia.org/ontology/water>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_water.ttl
grep '<http://dbpedia.org/ontology/weight>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_weight.ttl
grep '<http://dbpedia.org/ontology/width>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_width.ttl
grep '<http://dbpedia.org/ontology/wins>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_wins.ttl
grep '<http://dbpedia.org/ontology/writer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_writer.ttl
grep '<http://dbpedia.org/ontology/yearOfConstruction>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_yearOfConstruction.ttl
grep '<http://dbpedia.org/ontology/youthClub>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_youthClub.ttl
grep '<http://dbpedia.org/ontology/zdb>' ../resources/de//turtle/mappingbased_literals_de.ttl>>../resources/de//property/dbo_zdb.ttl
