#!/bin/sh
grep '<http://dbpedia.org/ontology/achievement>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_achievement.ttl
grep '<http://dbpedia.org/ontology/affiliation>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_affiliation.ttl
grep '<http://dbpedia.org/ontology/album>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_album.ttl
grep '<http://dbpedia.org/ontology/almaMater>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_almaMater.ttl
grep '<http://dbpedia.org/ontology/archipelago>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_archipelago.ttl
grep '<http://dbpedia.org/ontology/architecturalStyle>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_architecturalStyle.ttl
grep '<http://dbpedia.org/ontology/artist>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_artist.ttl
grep '<http://dbpedia.org/ontology/associateEditor>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_associateEditor.ttl
grep '<http://dbpedia.org/ontology/authority>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_authority.ttl
grep '<http://dbpedia.org/ontology/award>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_award.ttl
grep '<http://dbpedia.org/ontology/battle>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_battle.ttl
grep '<http://dbpedia.org/ontology/binomialAuthority>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_binomialAuthority.ttl
grep '<http://dbpedia.org/ontology/broadcastArea>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_broadcastArea.ttl
grep '<http://dbpedia.org/ontology/builder>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_builder.ttl
grep '<http://dbpedia.org/ontology/campus>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_campus.ttl
grep '<http://dbpedia.org/ontology/category>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_category.ttl
grep '<http://dbpedia.org/ontology/chairperson>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_chairperson.ttl
grep '<http://dbpedia.org/ontology/channel>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_channel.ttl
grep '<http://dbpedia.org/ontology/child>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_child.ttl
grep '<http://dbpedia.org/ontology/citizenship>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_citizenship.ttl
grep '<http://dbpedia.org/ontology/class>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_class.ttl
grep '<http://dbpedia.org/ontology/colour>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_colour.ttl
grep '<http://dbpedia.org/ontology/commune>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_commune.ttl
grep '<http://dbpedia.org/ontology/compiler>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_compiler.ttl
grep '<http://dbpedia.org/ontology/computingInput>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_computingInput.ttl
grep '<http://dbpedia.org/ontology/computingPlatform>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_computingPlatform.ttl
grep '<http://dbpedia.org/ontology/constructionMaterial>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_constructionMaterial.ttl
grep '<http://dbpedia.org/ontology/country>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_country.ttl
grep '<http://dbpedia.org/ontology/coverArtist>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_coverArtist.ttl
grep '<http://dbpedia.org/ontology/curator>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_curator.ttl
grep '<http://dbpedia.org/ontology/currentProduction>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_currentProduction.ttl
grep '<http://dbpedia.org/ontology/deathCause>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_deathCause.ttl
grep '<http://dbpedia.org/ontology/debutTeam>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_debutTeam.ttl
grep '<http://dbpedia.org/ontology/deputy>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_deputy.ttl
grep '<http://dbpedia.org/ontology/destination>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_destination.ttl
grep '<http://dbpedia.org/ontology/director>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_director.ttl
grep '<http://dbpedia.org/ontology/distributor>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_distributor.ttl
grep '<http://dbpedia.org/ontology/doctoralAdvisor>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_doctoralAdvisor.ttl
grep '<http://dbpedia.org/ontology/domain>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_domain.ttl
grep '<http://dbpedia.org/ontology/editing>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_editing.ttl
grep '<http://dbpedia.org/ontology/education>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_education.ttl
grep '<http://dbpedia.org/ontology/emmyAward>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_emmyAward.ttl
grep '<http://dbpedia.org/ontology/ethnicity>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_ethnicity.ttl
grep '<http://dbpedia.org/ontology/executiveProducer>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_executiveProducer.ttl
grep '<http://dbpedia.org/ontology/family>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_family.ttl
grep '<http://dbpedia.org/ontology/firstAscentPerson>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_firstAscentPerson.ttl
grep '<http://dbpedia.org/ontology/firstWin>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_firstWin.ttl
grep '<http://dbpedia.org/ontology/format>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_format.ttl
grep '<http://dbpedia.org/ontology/formerTeam>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_formerTeam.ttl
grep '<http://dbpedia.org/ontology/foundedBy>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_foundedBy.ttl
grep '<http://dbpedia.org/ontology/gameArtist>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_gameArtist.ttl
grep '<http://dbpedia.org/ontology/gender>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_gender.ttl
grep '<http://dbpedia.org/ontology/genus>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_genus.ttl
grep '<http://dbpedia.org/ontology/goyaAward>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_goyaAward.ttl
grep '<http://dbpedia.org/ontology/guest>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_guest.ttl
grep '<http://dbpedia.org/ontology/headquarter>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_headquarter.ttl
grep '<http://dbpedia.org/ontology/homeStadium>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_homeStadium.ttl
grep '<http://dbpedia.org/ontology/hubAirport>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_hubAirport.ttl
grep '<http://dbpedia.org/ontology/ideology>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_ideology.ttl
grep '<http://dbpedia.org/ontology/industry>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_industry.ttl
grep '<http://dbpedia.org/ontology/influencedBy>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_influencedBy.ttl
grep '<http://dbpedia.org/ontology/internationalAffiliation>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_internationalAffiliation.ttl
grep '<http://dbpedia.org/ontology/keyPerson>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_keyPerson.ttl
grep '<http://dbpedia.org/ontology/knownFor>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_knownFor.ttl
grep '<http://dbpedia.org/ontology/languageFamily>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_languageFamily.ttl
grep '<http://dbpedia.org/ontology/largestCity>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_largestCity.ttl
grep '<http://dbpedia.org/ontology/leader>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_leader.ttl
grep '<http://dbpedia.org/ontology/league>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_league.ttl
grep '<http://dbpedia.org/ontology/literaryGenre>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_literaryGenre.ttl
grep '<http://dbpedia.org/ontology/location>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_location.ttl
grep '<http://dbpedia.org/ontology/locationCountry>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_locationCountry.ttl
grep '<http://dbpedia.org/ontology/mainOrgan>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_mainOrgan.ttl
grep '<http://dbpedia.org/ontology/management>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_management.ttl
grep '<http://dbpedia.org/ontology/manufacturer>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_manufacturer.ttl
grep '<http://dbpedia.org/ontology/mayor>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_mayor.ttl
grep '<http://dbpedia.org/ontology/militaryRank>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_militaryRank.ttl
grep '<http://dbpedia.org/ontology/monarch>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_monarch.ttl
grep '<http://dbpedia.org/ontology/mouthPosition>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_mouthPosition.ttl
grep '<http://dbpedia.org/ontology/municipality>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_municipality.ttl
grep '<http://dbpedia.org/ontology/musicalArtist>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_musicalArtist.ttl
grep '<http://dbpedia.org/ontology/musicians>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_musicians.ttl
grep '<http://dbpedia.org/ontology/nationalTeam>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_nationalTeam.ttl
grep '<http://dbpedia.org/ontology/network>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_network.ttl
grep '<http://dbpedia.org/ontology/notableWork>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_notableWork.ttl
grep '<http://dbpedia.org/ontology/officerInCharge>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_officerInCharge.ttl
grep '<http://dbpedia.org/ontology/officialOpenedBy>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_officialOpenedBy.ttl
grep '<http://dbpedia.org/ontology/olympicOathSwornByJudge>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_olympicOathSwornByJudge.ttl
grep '<http://dbpedia.org/ontology/operatingSystem>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_operatingSystem.ttl
grep '<http://dbpedia.org/ontology/order>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_order.ttl
grep '<http://dbpedia.org/ontology/owner>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_owner.ttl
grep '<http://dbpedia.org/ontology/owningOrganisation>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_owningOrganisation.ttl
grep '<http://dbpedia.org/ontology/parentOrganisation>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_parentOrganisation.ttl
grep '<http://dbpedia.org/ontology/partner>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_partner.ttl
grep '<http://dbpedia.org/ontology/period>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_period.ttl
grep '<http://dbpedia.org/ontology/personFunction>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_personFunction.ttl
grep '<http://dbpedia.org/ontology/picture>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_picture.ttl
grep '<http://dbpedia.org/ontology/pictureFormat>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_pictureFormat.ttl
grep '<http://dbpedia.org/ontology/placeOfBurial>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_placeOfBurial.ttl
grep '<http://dbpedia.org/ontology/precursor>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_precursor.ttl
grep '<http://dbpedia.org/ontology/premierePlace>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_premierePlace.ttl
grep '<http://dbpedia.org/ontology/president>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_president.ttl
grep '<http://dbpedia.org/ontology/previousWork>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_previousWork.ttl
grep '<http://dbpedia.org/ontology/principal>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_principal.ttl
grep '<http://dbpedia.org/ontology/product>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_product.ttl
grep '<http://dbpedia.org/ontology/profession>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_profession.ttl
grep '<http://dbpedia.org/ontology/programmingLanguage>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_programmingLanguage.ttl
grep '<http://dbpedia.org/ontology/provost>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_provost.ttl
grep '<http://dbpedia.org/ontology/recordLabel>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_recordLabel.ttl
grep '<http://dbpedia.org/ontology/rector>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_rector.ttl
grep '<http://dbpedia.org/ontology/regionServed>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_regionServed.ttl
grep '<http://dbpedia.org/ontology/relation>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_relation.ttl
grep '<http://dbpedia.org/ontology/religion>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_religion.ttl
grep '<http://dbpedia.org/ontology/religiousOrder>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_religiousOrder.ttl
grep '<http://dbpedia.org/ontology/riverMouth>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_riverMouth.ttl
grep '<http://dbpedia.org/ontology/routeEndLocation>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_routeEndLocation.ttl
grep '<http://dbpedia.org/ontology/routeStart>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_routeStart.ttl
grep '<http://dbpedia.org/ontology/saint>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_saint.ttl
grep '<http://dbpedia.org/ontology/season>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_season.ttl
grep '<http://dbpedia.org/ontology/series>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_series.ttl
grep '<http://dbpedia.org/ontology/servingRailwayLine>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_servingRailwayLine.ttl
grep '<http://dbpedia.org/ontology/sisterStation>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_sisterStation.ttl
grep '<http://dbpedia.org/ontology/sourcePlace>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_sourcePlace.ttl
grep '<http://dbpedia.org/ontology/spokenIn>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_spokenIn.ttl
grep '<http://dbpedia.org/ontology/sport>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_sport.ttl
grep '<http://dbpedia.org/ontology/spouse>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_spouse.ttl
grep '<http://dbpedia.org/ontology/state>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_state.ttl
grep '<http://dbpedia.org/ontology/subsequentInfrastructure>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_subsequentInfrastructure.ttl
grep '<http://dbpedia.org/ontology/subsidiary>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_subsidiary.ttl
grep '<http://dbpedia.org/ontology/taoiseach>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_taoiseach.ttl
grep '<http://dbpedia.org/ontology/team>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_team.ttl
grep '<http://dbpedia.org/ontology/thumbnail>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_thumbnail.ttl
grep '<http://dbpedia.org/ontology/torchBearer>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_torchBearer.ttl
grep '<http://dbpedia.org/ontology/trainer>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_trainer.ttl
grep '<http://dbpedia.org/ontology/type>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_type.ttl
grep '<http://dbpedia.org/ontology/veneratedIn>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_veneratedIn.ttl
grep '<http://dbpedia.org/ontology/vicePrincipal>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_vicePrincipal.ttl
grep '<http://dbpedia.org/ontology/voiceType>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_voiceType.ttl
grep '<http://dbpedia.org/ontology/wikiPageWikiLink>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_wikiPageWikiLink.ttl
grep '<http://dbpedia.org/ontology/youthWing>' ../resources/es//turtle/mappingbased_objects_es.ttl>>../resources/es//property/dbo_youthWing.ttl
