#!/bin/sh
grep '<http://dbpedia.org/ontology/academicDiscipline>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_academicDiscipline.ttl
grep '<http://dbpedia.org/ontology/addressInRoad>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_addressInRoad.ttl
grep '<http://dbpedia.org/ontology/administrativeDistrict>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_administrativeDistrict.ttl
grep '<http://dbpedia.org/ontology/affiliation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_affiliation.ttl
grep '<http://dbpedia.org/ontology/aircraftAttack>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_aircraftAttack.ttl
grep '<http://dbpedia.org/ontology/aircraftElectronic>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_aircraftElectronic.ttl
grep '<http://dbpedia.org/ontology/aircraftHelicopter>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_aircraftHelicopter.ttl
grep '<http://dbpedia.org/ontology/aircraftHelicopterCargo>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_aircraftHelicopterCargo.ttl
grep '<http://dbpedia.org/ontology/aircraftHelicopterObservation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_aircraftHelicopterObservation.ttl
grep '<http://dbpedia.org/ontology/aircraftHelicopterUtility>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_aircraftHelicopterUtility.ttl
grep '<http://dbpedia.org/ontology/aircraftPatrol>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_aircraftPatrol.ttl
grep '<http://dbpedia.org/ontology/aircraftTrainer>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_aircraftTrainer.ttl
grep '<http://dbpedia.org/ontology/album>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_album.ttl
grep '<http://dbpedia.org/ontology/almaMater>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_almaMater.ttl
grep '<http://dbpedia.org/ontology/animal>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_animal.ttl
grep '<http://dbpedia.org/ontology/anthem>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_anthem.ttl
grep '<http://dbpedia.org/ontology/archipelago>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_archipelago.ttl
grep '<http://dbpedia.org/ontology/architecturalStyle>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_architecturalStyle.ttl
grep '<http://dbpedia.org/ontology/arrondissement>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_arrondissement.ttl
grep '<http://dbpedia.org/ontology/artist>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_artist.ttl
grep '<http://dbpedia.org/ontology/assistantPrincipal>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_assistantPrincipal.ttl
grep '<http://dbpedia.org/ontology/associateEditor>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_associateEditor.ttl
grep '<http://dbpedia.org/ontology/associatedBand>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_associatedBand.ttl
grep '<http://dbpedia.org/ontology/associatedRocket>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_associatedRocket.ttl
grep '<http://dbpedia.org/ontology/athletics>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_athletics.ttl
grep '<http://dbpedia.org/ontology/authority>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_authority.ttl
grep '<http://dbpedia.org/ontology/availableSmartCard>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_availableSmartCard.ttl
grep '<http://dbpedia.org/ontology/bandMember>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_bandMember.ttl
grep '<http://dbpedia.org/ontology/battle>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_battle.ttl
grep '<http://dbpedia.org/ontology/beatifiedPlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_beatifiedPlace.ttl
grep '<http://dbpedia.org/ontology/billed>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_billed.ttl
grep '<http://dbpedia.org/ontology/binomialAuthority>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_binomialAuthority.ttl
grep '<http://dbpedia.org/ontology/birthPlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_birthPlace.ttl
grep '<http://dbpedia.org/ontology/board>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_board.ttl
grep '<http://dbpedia.org/ontology/bodyStyle>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_bodyStyle.ttl
grep '<http://dbpedia.org/ontology/boilerPressure>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_boilerPressure.ttl
grep '<http://dbpedia.org/ontology/borough>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_borough.ttl
grep '<http://dbpedia.org/ontology/branchTo>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_branchTo.ttl
grep '<http://dbpedia.org/ontology/breeder>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_breeder.ttl
grep '<http://dbpedia.org/ontology/broadcastNetwork>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_broadcastNetwork.ttl
grep '<http://dbpedia.org/ontology/builder>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_builder.ttl
grep '<http://dbpedia.org/ontology/campus>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_campus.ttl
grep '<http://dbpedia.org/ontology/canonizedPlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_canonizedPlace.ttl
grep '<http://dbpedia.org/ontology/capital>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_capital.ttl
grep '<http://dbpedia.org/ontology/capitalMountain>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_capitalMountain.ttl
grep '<http://dbpedia.org/ontology/capitalRegion>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_capitalRegion.ttl
grep '<http://dbpedia.org/ontology/ceo>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_ceo.ttl
grep '<http://dbpedia.org/ontology/chain>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_chain.ttl
grep '<http://dbpedia.org/ontology/chairman>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_chairman.ttl
grep '<http://dbpedia.org/ontology/champion>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_champion.ttl
grep '<http://dbpedia.org/ontology/championInDoubleMale>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_championInDoubleMale.ttl
grep '<http://dbpedia.org/ontology/championInSingleFemale>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_championInSingleFemale.ttl
grep '<http://dbpedia.org/ontology/chancellor>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_chancellor.ttl
grep '<http://dbpedia.org/ontology/chaplain>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_chaplain.ttl
grep '<http://dbpedia.org/ontology/chiefEditor>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_chiefEditor.ttl
grep '<http://dbpedia.org/ontology/childOrganisation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_childOrganisation.ttl
grep '<http://dbpedia.org/ontology/cinematography>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_cinematography.ttl
grep '<http://dbpedia.org/ontology/city>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_city.ttl
grep '<http://dbpedia.org/ontology/closingFilm>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_closingFilm.ttl
grep '<http://dbpedia.org/ontology/clubsRecordGoalscorer>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_clubsRecordGoalscorer.ttl
grep '<http://dbpedia.org/ontology/coachedTeam>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_coachedTeam.ttl
grep '<http://dbpedia.org/ontology/colour>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_colour.ttl
grep '<http://dbpedia.org/ontology/commander>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_commander.ttl
grep '<http://dbpedia.org/ontology/company>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_company.ttl
grep '<http://dbpedia.org/ontology/compiler>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_compiler.ttl
grep '<http://dbpedia.org/ontology/composer>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_composer.ttl
grep '<http://dbpedia.org/ontology/congressionalDistrict>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_congressionalDistrict.ttl
grep '<http://dbpedia.org/ontology/constructionMaterial>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_constructionMaterial.ttl
grep '<http://dbpedia.org/ontology/councilArea>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_councilArea.ttl
grep '<http://dbpedia.org/ontology/countryOrigin>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_countryOrigin.ttl
grep '<http://dbpedia.org/ontology/countryWithFirstSatellite>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_countryWithFirstSatellite.ttl
grep '<http://dbpedia.org/ontology/countryWithFirstSpaceflight>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_countryWithFirstSpaceflight.ttl
grep '<http://dbpedia.org/ontology/countySeat>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_countySeat.ttl
grep '<http://dbpedia.org/ontology/cpu>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_cpu.ttl
grep '<http://dbpedia.org/ontology/creator>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_creator.ttl
grep '<http://dbpedia.org/ontology/crosses>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_crosses.ttl
grep '<http://dbpedia.org/ontology/curator>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_curator.ttl
grep '<http://dbpedia.org/ontology/currentMember>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_currentMember.ttl
grep '<http://dbpedia.org/ontology/currentProduction>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_currentProduction.ttl
grep '<http://dbpedia.org/ontology/dam>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_dam.ttl
grep '<http://dbpedia.org/ontology/damsire>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_damsire.ttl
grep '<http://dbpedia.org/ontology/dean>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_dean.ttl
grep '<http://dbpedia.org/ontology/deathPlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_deathPlace.ttl
grep '<http://dbpedia.org/ontology/denomination>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_denomination.ttl
grep '<http://dbpedia.org/ontology/deputy>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_deputy.ttl
grep '<http://dbpedia.org/ontology/designCompany>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_designCompany.ttl
grep '<http://dbpedia.org/ontology/destination>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_destination.ttl
grep '<http://dbpedia.org/ontology/director>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_director.ttl
grep '<http://dbpedia.org/ontology/discoverer>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_discoverer.ttl
grep '<http://dbpedia.org/ontology/distributingLabel>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_distributingLabel.ttl
grep '<http://dbpedia.org/ontology/district>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_district.ttl
grep '<http://dbpedia.org/ontology/doctoralAdvisor>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_doctoralAdvisor.ttl
grep '<http://dbpedia.org/ontology/domain>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_domain.ttl
grep '<http://dbpedia.org/ontology/drainsFrom>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_drainsFrom.ttl
grep '<http://dbpedia.org/ontology/editing>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_editing.ttl
grep '<http://dbpedia.org/ontology/education>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_education.ttl
grep '<http://dbpedia.org/ontology/endPoint>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_endPoint.ttl
grep '<http://dbpedia.org/ontology/engineType>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_engineType.ttl
grep '<http://dbpedia.org/ontology/equipment>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_equipment.ttl
grep '<http://dbpedia.org/ontology/ethnicGroup>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_ethnicGroup.ttl
grep '<http://dbpedia.org/ontology/europeanAffiliation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_europeanAffiliation.ttl
grep '<http://dbpedia.org/ontology/event>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_event.ttl
grep '<http://dbpedia.org/ontology/family>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_family.ttl
grep '<http://dbpedia.org/ontology/fastestDriverCountry>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_fastestDriverCountry.ttl
grep '<http://dbpedia.org/ontology/federalState>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_federalState.ttl
grep '<http://dbpedia.org/ontology/film>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_film.ttl
grep '<http://dbpedia.org/ontology/firstDriver>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_firstDriver.ttl
grep '<http://dbpedia.org/ontology/firstDriverTeam>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_firstDriverTeam.ttl
grep '<http://dbpedia.org/ontology/firstLaunchRocket>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_firstLaunchRocket.ttl
grep '<http://dbpedia.org/ontology/firstPopularVote>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_firstPopularVote.ttl
grep '<http://dbpedia.org/ontology/firstWin>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_firstWin.ttl
grep '<http://dbpedia.org/ontology/flagBearer>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_flagBearer.ttl
grep '<http://dbpedia.org/ontology/format>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_format.ttl
grep '<http://dbpedia.org/ontology/formerBroadcastNetwork>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_formerBroadcastNetwork.ttl
grep '<http://dbpedia.org/ontology/formerCoach>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_formerCoach.ttl
grep '<http://dbpedia.org/ontology/formerPartner>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_formerPartner.ttl
grep '<http://dbpedia.org/ontology/foundationPlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_foundationPlace.ttl
grep '<http://dbpedia.org/ontology/founder>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_founder.ttl
grep '<http://dbpedia.org/ontology/frazioni>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_frazioni.ttl
grep '<http://dbpedia.org/ontology/gameArtist>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_gameArtist.ttl
grep '<http://dbpedia.org/ontology/garrison>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_garrison.ttl
grep '<http://dbpedia.org/ontology/generalManager>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_generalManager.ttl
grep '<http://dbpedia.org/ontology/genus>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_genus.ttl
grep '<http://dbpedia.org/ontology/governingBody>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_governingBody.ttl
grep '<http://dbpedia.org/ontology/governmentCountry>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_governmentCountry.ttl
grep '<http://dbpedia.org/ontology/governmentPlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_governmentPlace.ttl
grep '<http://dbpedia.org/ontology/governmentType>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_governmentType.ttl
grep '<http://dbpedia.org/ontology/governorGeneral>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_governorGeneral.ttl
grep '<http://dbpedia.org/ontology/grandsire>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_grandsire.ttl
grep '<http://dbpedia.org/ontology/growingGrape>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_growingGrape.ttl
grep '<http://dbpedia.org/ontology/hasJunctionWith>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_hasJunctionWith.ttl
grep '<http://dbpedia.org/ontology/head>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_head.ttl
grep '<http://dbpedia.org/ontology/headChef>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_headChef.ttl
grep '<http://dbpedia.org/ontology/headteacher>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_headteacher.ttl
grep '<http://dbpedia.org/ontology/highestMountain>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_highestMountain.ttl
grep '<http://dbpedia.org/ontology/highestRegion>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_highestRegion.ttl
grep '<http://dbpedia.org/ontology/highschool>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_highschool.ttl
grep '<http://dbpedia.org/ontology/homeArena>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_homeArena.ttl
grep '<http://dbpedia.org/ontology/homeport>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_homeport.ttl
grep '<http://dbpedia.org/ontology/honours>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_honours.ttl
grep '<http://dbpedia.org/ontology/hubAirport>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_hubAirport.ttl
grep '<http://dbpedia.org/ontology/ideology>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_ideology.ttl
grep '<http://dbpedia.org/ontology/incumbent>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_incumbent.ttl
grep '<http://dbpedia.org/ontology/inflow>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_inflow.ttl
grep '<http://dbpedia.org/ontology/influencedBy>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_influencedBy.ttl
grep '<http://dbpedia.org/ontology/innervates>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_innervates.ttl
grep '<http://dbpedia.org/ontology/instrument>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_instrument.ttl
grep '<http://dbpedia.org/ontology/internationalAffiliation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_internationalAffiliation.ttl
grep '<http://dbpedia.org/ontology/isPartOfAnatomicalStructure>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_isPartOfAnatomicalStructure.ttl
grep '<http://dbpedia.org/ontology/isPartOfWineRegion>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_isPartOfWineRegion.ttl
grep '<http://dbpedia.org/ontology/jockey>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_jockey.ttl
grep '<http://dbpedia.org/ontology/jurisdiction>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_jurisdiction.ttl
grep '<http://dbpedia.org/ontology/kingdom>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_kingdom.ttl
grep '<http://dbpedia.org/ontology/language>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_language.ttl
grep '<http://dbpedia.org/ontology/languageRegulator>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_languageRegulator.ttl
grep '<http://dbpedia.org/ontology/largestSettlement>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_largestSettlement.ttl
grep '<http://dbpedia.org/ontology/lastFlight>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_lastFlight.ttl
grep '<http://dbpedia.org/ontology/lastRace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_lastRace.ttl
grep '<http://dbpedia.org/ontology/launchSite>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_launchSite.ttl
grep '<http://dbpedia.org/ontology/leader>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_leader.ttl
grep '<http://dbpedia.org/ontology/leaderParty>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_leaderParty.ttl
grep '<http://dbpedia.org/ontology/leftChild>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_leftChild.ttl
grep '<http://dbpedia.org/ontology/legalForm>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_legalForm.ttl
grep '<http://dbpedia.org/ontology/lieutenancyArea>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_lieutenancyArea.ttl
grep '<http://dbpedia.org/ontology/literaryGenre>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_literaryGenre.ttl
grep '<http://dbpedia.org/ontology/locatedInArea>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_locatedInArea.ttl
grep '<http://dbpedia.org/ontology/locationCity>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_locationCity.ttl
grep '<http://dbpedia.org/ontology/lounge>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_lounge.ttl
grep '<http://dbpedia.org/ontology/lowestPlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_lowestPlace.ttl
grep '<http://dbpedia.org/ontology/lowestState>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_lowestState.ttl
grep '<http://dbpedia.org/ontology/lyrics>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_lyrics.ttl
grep '<http://dbpedia.org/ontology/maidenFlightRocket>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_maidenFlightRocket.ttl
grep '<http://dbpedia.org/ontology/mainOrgan>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_mainOrgan.ttl
grep '<http://dbpedia.org/ontology/majorIsland>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_majorIsland.ttl
grep '<http://dbpedia.org/ontology/management>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_management.ttl
grep '<http://dbpedia.org/ontology/managementPlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_managementPlace.ttl
grep '<http://dbpedia.org/ontology/managerClub>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_managerClub.ttl
grep '<http://dbpedia.org/ontology/manufacturer>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_manufacturer.ttl
grep '<http://dbpedia.org/ontology/march>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_march.ttl
grep '<http://dbpedia.org/ontology/mediaType>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_mediaType.ttl
grep '<http://dbpedia.org/ontology/mergedIntoParty>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_mergedIntoParty.ttl
grep '<http://dbpedia.org/ontology/militaryBranch>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_militaryBranch.ttl
grep '<http://dbpedia.org/ontology/militaryUnit>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_militaryUnit.ttl
grep '<http://dbpedia.org/ontology/monarch>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_monarch.ttl
grep '<http://dbpedia.org/ontology/mountainRange>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_mountainRange.ttl
grep '<http://dbpedia.org/ontology/mouthMountain>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_mouthMountain.ttl
grep '<http://dbpedia.org/ontology/mouthRegion>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_mouthRegion.ttl
grep '<http://dbpedia.org/ontology/municipality>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_municipality.ttl
grep '<http://dbpedia.org/ontology/musicBy>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_musicBy.ttl
grep '<http://dbpedia.org/ontology/musicFusionGenre>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_musicFusionGenre.ttl
grep '<http://dbpedia.org/ontology/musicalArtist>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_musicalArtist.ttl
grep '<http://dbpedia.org/ontology/mythology>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_mythology.ttl
grep '<http://dbpedia.org/ontology/narrator>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_narrator.ttl
grep '<http://dbpedia.org/ontology/nationalTeam>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_nationalTeam.ttl
grep '<http://dbpedia.org/ontology/nearestCity>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_nearestCity.ttl
grep '<http://dbpedia.org/ontology/nerve>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_nerve.ttl
grep '<http://dbpedia.org/ontology/nextEvent>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_nextEvent.ttl
grep '<http://dbpedia.org/ontology/nominee>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_nominee.ttl
grep '<http://dbpedia.org/ontology/notableCommander>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_notableCommander.ttl
grep '<http://dbpedia.org/ontology/notableStudent>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_notableStudent.ttl
grep '<http://dbpedia.org/ontology/notableWork>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_notableWork.ttl
grep '<http://dbpedia.org/ontology/numberOfClassrooms>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_numberOfClassrooms.ttl
grep '<http://dbpedia.org/ontology/officerInCharge>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_officerInCharge.ttl
grep '<http://dbpedia.org/ontology/oilSystem>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_oilSystem.ttl
grep '<http://dbpedia.org/ontology/openingTheme>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_openingTheme.ttl
grep '<http://dbpedia.org/ontology/operator>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_operator.ttl
grep '<http://dbpedia.org/ontology/order>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_order.ttl
grep '<http://dbpedia.org/ontology/organisation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_organisation.ttl
grep '<http://dbpedia.org/ontology/originalEndPoint>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_originalEndPoint.ttl
grep '<http://dbpedia.org/ontology/originalStartPoint>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_originalStartPoint.ttl
grep '<http://dbpedia.org/ontology/otherParty>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_otherParty.ttl
grep '<http://dbpedia.org/ontology/owner>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_owner.ttl
grep '<http://dbpedia.org/ontology/owningOrganisation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_owningOrganisation.ttl
grep '<http://dbpedia.org/ontology/parentCompany>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_parentCompany.ttl
grep '<http://dbpedia.org/ontology/parentOrganisation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_parentOrganisation.ttl
grep '<http://dbpedia.org/ontology/part>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_part.ttl
grep '<http://dbpedia.org/ontology/party>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_party.ttl
grep '<http://dbpedia.org/ontology/pastor>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_pastor.ttl
grep '<http://dbpedia.org/ontology/person>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_person.ttl
grep '<http://dbpedia.org/ontology/photographer>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_photographer.ttl
grep '<http://dbpedia.org/ontology/picture>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_picture.ttl
grep '<http://dbpedia.org/ontology/place>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_place.ttl
grep '<http://dbpedia.org/ontology/plant>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_plant.ttl
grep '<http://dbpedia.org/ontology/poleDriverCountry>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_poleDriverCountry.ttl
grep '<http://dbpedia.org/ontology/politicalPartyInLegislature>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_politicalPartyInLegislature.ttl
grep '<http://dbpedia.org/ontology/populationPlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_populationPlace.ttl
grep '<http://dbpedia.org/ontology/position>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_position.ttl
grep '<http://dbpedia.org/ontology/precursor>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_precursor.ttl
grep '<http://dbpedia.org/ontology/premierePlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_premierePlace.ttl
grep '<http://dbpedia.org/ontology/president>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_president.ttl
grep '<http://dbpedia.org/ontology/previousEvent>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_previousEvent.ttl
grep '<http://dbpedia.org/ontology/previousWork>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_previousWork.ttl
grep '<http://dbpedia.org/ontology/principal>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_principal.ttl
grep '<http://dbpedia.org/ontology/principalEngineer>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_principalEngineer.ttl
grep '<http://dbpedia.org/ontology/product>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_product.ttl
grep '<http://dbpedia.org/ontology/programmeFormat>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_programmeFormat.ttl
grep '<http://dbpedia.org/ontology/projectCoordinator>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_projectCoordinator.ttl
grep '<http://dbpedia.org/ontology/promotion>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_promotion.ttl
grep '<http://dbpedia.org/ontology/prospectTeam>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_prospectTeam.ttl
grep '<http://dbpedia.org/ontology/provost>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_provost.ttl
grep '<http://dbpedia.org/ontology/race>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_race.ttl
grep '<http://dbpedia.org/ontology/railwayLineUsingTunnel>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_railwayLineUsingTunnel.ttl
grep '<http://dbpedia.org/ontology/ratio>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_ratio.ttl
grep '<http://dbpedia.org/ontology/recentWinner>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_recentWinner.ttl
grep '<http://dbpedia.org/ontology/recordedIn>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_recordedIn.ttl
grep '<http://dbpedia.org/ontology/region>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_region.ttl
grep '<http://dbpedia.org/ontology/regionalLanguage>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_regionalLanguage.ttl
grep '<http://dbpedia.org/ontology/relatedMeanOfTransportation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_relatedMeanOfTransportation.ttl
grep '<http://dbpedia.org/ontology/relative>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_relative.ttl
grep '<http://dbpedia.org/ontology/religion>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_religion.ttl
grep '<http://dbpedia.org/ontology/religiousHeadLabel>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_religiousHeadLabel.ttl
grep '<http://dbpedia.org/ontology/restingPlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_restingPlace.ttl
grep '<http://dbpedia.org/ontology/rightChild>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_rightChild.ttl
grep '<http://dbpedia.org/ontology/rival>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_rival.ttl
grep '<http://dbpedia.org/ontology/riverBranch>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_riverBranch.ttl
grep '<http://dbpedia.org/ontology/riverMouth>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_riverMouth.ttl
grep '<http://dbpedia.org/ontology/routeEnd>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_routeEnd.ttl
grep '<http://dbpedia.org/ontology/routeJunction>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_routeJunction.ttl
grep '<http://dbpedia.org/ontology/routeStartLocation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_routeStartLocation.ttl
grep '<http://dbpedia.org/ontology/runningMate>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_runningMate.ttl
grep '<http://dbpedia.org/ontology/saint>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_saint.ttl
grep '<http://dbpedia.org/ontology/school>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_school.ttl
grep '<http://dbpedia.org/ontology/schoolPatron>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_schoolPatron.ttl
grep '<http://dbpedia.org/ontology/secondCommander>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_secondCommander.ttl
grep '<http://dbpedia.org/ontology/secondDriverCountry>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_secondDriverCountry.ttl
grep '<http://dbpedia.org/ontology/secondPopularVote>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_secondPopularVote.ttl
grep '<http://dbpedia.org/ontology/secretaryGeneral>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_secretaryGeneral.ttl
grep '<http://dbpedia.org/ontology/series>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_series.ttl
grep '<http://dbpedia.org/ontology/servingRailwayLine>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_servingRailwayLine.ttl
grep '<http://dbpedia.org/ontology/show>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_show.ttl
grep '<http://dbpedia.org/ontology/significantBuilding>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_significantBuilding.ttl
grep '<http://dbpedia.org/ontology/significantProject>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_significantProject.ttl
grep '<http://dbpedia.org/ontology/similar>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_similar.ttl
grep '<http://dbpedia.org/ontology/sisterCollege>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_sisterCollege.ttl
grep '<http://dbpedia.org/ontology/sisterStation>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_sisterStation.ttl
grep '<http://dbpedia.org/ontology/sourceConfluence>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_sourceConfluence.ttl
grep '<http://dbpedia.org/ontology/sourceConfluencePlace>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_sourceConfluencePlace.ttl
grep '<http://dbpedia.org/ontology/sourceConfluenceState>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_sourceConfluenceState.ttl
grep '<http://dbpedia.org/ontology/sourceMountain>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_sourceMountain.ttl
grep '<http://dbpedia.org/ontology/sourceRegion>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_sourceRegion.ttl
grep '<http://dbpedia.org/ontology/splitFromParty>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_splitFromParty.ttl
grep '<http://dbpedia.org/ontology/spokesperson>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_spokesperson.ttl
grep '<http://dbpedia.org/ontology/sportCountry>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_sportCountry.ttl
grep '<http://dbpedia.org/ontology/spouse>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_spouse.ttl
grep '<http://dbpedia.org/ontology/starring>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_starring.ttl
grep '<http://dbpedia.org/ontology/state>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_state.ttl
grep '<http://dbpedia.org/ontology/statisticLabel>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_statisticLabel.ttl
grep '<http://dbpedia.org/ontology/stylisticOrigin>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_stylisticOrigin.ttl
grep '<http://dbpedia.org/ontology/subsequentInfrastructure>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_subsequentInfrastructure.ttl
grep '<http://dbpedia.org/ontology/subsidiary>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_subsidiary.ttl
grep '<http://dbpedia.org/ontology/summerAppearances>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_summerAppearances.ttl
grep '<http://dbpedia.org/ontology/supplies>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_supplies.ttl
grep '<http://dbpedia.org/ontology/targetAirport>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_targetAirport.ttl
grep '<http://dbpedia.org/ontology/team>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_team.ttl
grep '<http://dbpedia.org/ontology/tenant>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_tenant.ttl
grep '<http://dbpedia.org/ontology/thirdCommander>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_thirdCommander.ttl
grep '<http://dbpedia.org/ontology/thirdDriverCountry>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_thirdDriverCountry.ttl
grep '<http://dbpedia.org/ontology/timeZone>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_timeZone.ttl
grep '<http://dbpedia.org/ontology/training>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_training.ttl
grep '<http://dbpedia.org/ontology/trustee>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_trustee.ttl
grep '<http://dbpedia.org/ontology/twinTown>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_twinTown.ttl
grep '<http://dbpedia.org/ontology/typeOfElectrification>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_typeOfElectrification.ttl
grep '<http://dbpedia.org/ontology/university>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_university.ttl
grep '<http://dbpedia.org/ontology/usingCountry>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_usingCountry.ttl
grep '<http://dbpedia.org/ontology/vehicle>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_vehicle.ttl
grep '<http://dbpedia.org/ontology/veneratedIn>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_veneratedIn.ttl
grep '<http://dbpedia.org/ontology/vicePresident>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_vicePresident.ttl
grep '<http://dbpedia.org/ontology/vicePrincipal>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_vicePrincipal.ttl
grep '<http://dbpedia.org/ontology/victim>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_victim.ttl
grep '<http://dbpedia.org/ontology/voiceType>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_voiceType.ttl
grep '<http://dbpedia.org/ontology/webcast>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_webcast.ttl
grep '<http://dbpedia.org/ontology/wineProduced>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_wineProduced.ttl
grep '<http://dbpedia.org/ontology/winsAtAsia>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_winsAtAsia.ttl
grep '<http://dbpedia.org/ontology/winsAtChallenges>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_winsAtChallenges.ttl
grep '<http://dbpedia.org/ontology/winsAtJapan>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_winsAtJapan.ttl
grep '<http://dbpedia.org/ontology/winsAtLPGA>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_winsAtLPGA.ttl
grep '<http://dbpedia.org/ontology/winsAtNWIDE>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_winsAtNWIDE.ttl
grep '<http://dbpedia.org/ontology/winsAtPGA>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_winsAtPGA.ttl
grep '<http://dbpedia.org/ontology/winsInEurope>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_winsInEurope.ttl
grep '<http://dbpedia.org/ontology/writer>' ../resources/en//turtle/mappingbased_objects_en.ttl>>../resources/en//property/dbo_writer.ttl
