#!/bin/sh
grep '<http://dbpedia.org/ontology/administrativeDistrict>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_administrativeDistrict.ttl
grep '<http://dbpedia.org/ontology/affiliation>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_affiliation.ttl
grep '<http://dbpedia.org/ontology/aircraftBomber>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_aircraftBomber.ttl
grep '<http://dbpedia.org/ontology/aircraftFighter>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_aircraftFighter.ttl
grep '<http://dbpedia.org/ontology/alliance>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_alliance.ttl
grep '<http://dbpedia.org/ontology/archipelago>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_archipelago.ttl
grep '<http://dbpedia.org/ontology/architecturalStyle>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_architecturalStyle.ttl
grep '<http://dbpedia.org/ontology/artist>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_artist.ttl
grep '<http://dbpedia.org/ontology/associationOfLocalGovernment>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_associationOfLocalGovernment.ttl
grep '<http://dbpedia.org/ontology/author>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_author.ttl
grep '<http://dbpedia.org/ontology/award>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_award.ttl
grep '<http://dbpedia.org/ontology/basedOn>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_basedOn.ttl
grep '<http://dbpedia.org/ontology/birthPlace>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_birthPlace.ttl
grep '<http://dbpedia.org/ontology/breeder>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_breeder.ttl
grep '<http://dbpedia.org/ontology/broadcastNetwork>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_broadcastNetwork.ttl
grep '<http://dbpedia.org/ontology/buildingType>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_buildingType.ttl
grep '<http://dbpedia.org/ontology/capital>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_capital.ttl
grep '<http://dbpedia.org/ontology/ceo>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_ceo.ttl
grep '<http://dbpedia.org/ontology/champion>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_champion.ttl
grep '<http://dbpedia.org/ontology/choreographer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_choreographer.ttl
grep '<http://dbpedia.org/ontology/city>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_city.ttl
grep '<http://dbpedia.org/ontology/club>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_club.ttl
grep '<http://dbpedia.org/ontology/coach>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_coach.ttl
grep '<http://dbpedia.org/ontology/colour>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_colour.ttl
grep '<http://dbpedia.org/ontology/company>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_company.ttl
grep '<http://dbpedia.org/ontology/computingMedia>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_computingMedia.ttl
grep '<http://dbpedia.org/ontology/constellation>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_constellation.ttl
grep '<http://dbpedia.org/ontology/constructionMaterial>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_constructionMaterial.ttl
grep '<http://dbpedia.org/ontology/country>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_country.ttl
grep '<http://dbpedia.org/ontology/countySeat>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_countySeat.ttl
grep '<http://dbpedia.org/ontology/currency>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_currency.ttl
grep '<http://dbpedia.org/ontology/damsire>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_damsire.ttl
grep '<http://dbpedia.org/ontology/debutTeam>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_debutTeam.ttl
grep '<http://dbpedia.org/ontology/developer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_developer.ttl
grep '<http://dbpedia.org/ontology/discoverer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_discoverer.ttl
grep '<http://dbpedia.org/ontology/division>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_division.ttl
grep '<http://dbpedia.org/ontology/editing>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_editing.ttl
grep '<http://dbpedia.org/ontology/endPoint>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_endPoint.ttl
grep '<http://dbpedia.org/ontology/engineType>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_engineType.ttl
grep '<http://dbpedia.org/ontology/explorer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_explorer.ttl
grep '<http://dbpedia.org/ontology/firstRace>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_firstRace.ttl
grep '<http://dbpedia.org/ontology/formerBandMember>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_formerBandMember.ttl
grep '<http://dbpedia.org/ontology/formerTeam>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_formerTeam.ttl
grep '<http://dbpedia.org/ontology/founder>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_founder.ttl
grep '<http://dbpedia.org/ontology/garrison>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_garrison.ttl
grep '<http://dbpedia.org/ontology/government>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_government.ttl
grep '<http://dbpedia.org/ontology/ground>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_ground.ttl
grep '<http://dbpedia.org/ontology/head>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_head.ttl
grep '<http://dbpedia.org/ontology/highestMountain>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_highestMountain.ttl
grep '<http://dbpedia.org/ontology/homeport>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_homeport.ttl
grep '<http://dbpedia.org/ontology/hubAirport>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_hubAirport.ttl
grep '<http://dbpedia.org/ontology/inflow>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_inflow.ttl
grep '<http://dbpedia.org/ontology/influencedBy>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_influencedBy.ttl
grep '<http://dbpedia.org/ontology/intercommunality>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_intercommunality.ttl
grep '<http://dbpedia.org/ontology/island>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_island.ttl
grep '<http://dbpedia.org/ontology/jointCommunity>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_jointCommunity.ttl
grep '<http://dbpedia.org/ontology/language>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_language.ttl
grep '<http://dbpedia.org/ontology/largestCity>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_largestCity.ttl
grep '<http://dbpedia.org/ontology/lastRace>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_lastRace.ttl
grep '<http://dbpedia.org/ontology/launchVehicle>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_launchVehicle.ttl
grep '<http://dbpedia.org/ontology/leaderName>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_leaderName.ttl
grep '<http://dbpedia.org/ontology/league>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_league.ttl
grep '<http://dbpedia.org/ontology/license>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_license.ttl
grep '<http://dbpedia.org/ontology/locatedInArea>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_locatedInArea.ttl
grep '<http://dbpedia.org/ontology/locationCity>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_locationCity.ttl
grep '<http://dbpedia.org/ontology/lyrics>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_lyrics.ttl
grep '<http://dbpedia.org/ontology/majorIsland>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_majorIsland.ttl
grep '<http://dbpedia.org/ontology/managerClub>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_managerClub.ttl
grep '<http://dbpedia.org/ontology/map>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_map.ttl
grep '<http://dbpedia.org/ontology/mayor>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_mayor.ttl
grep '<http://dbpedia.org/ontology/mission>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_mission.ttl
grep '<http://dbpedia.org/ontology/municipality>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_municipality.ttl
grep '<http://dbpedia.org/ontology/musicComposer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_musicComposer.ttl
grep '<http://dbpedia.org/ontology/musicalArtist>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_musicalArtist.ttl
grep '<http://dbpedia.org/ontology/nationalTeam>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_nationalTeam.ttl
grep '<http://dbpedia.org/ontology/nearestCity>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_nearestCity.ttl
grep '<http://dbpedia.org/ontology/nerve>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_nerve.ttl
grep '<http://dbpedia.org/ontology/officialLanguage>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_officialLanguage.ttl
grep '<http://dbpedia.org/ontology/olympicOathSwornBy>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_olympicOathSwornBy.ttl
grep '<http://dbpedia.org/ontology/operatingSystem>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_operatingSystem.ttl
grep '<http://dbpedia.org/ontology/origin>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_origin.ttl
grep '<http://dbpedia.org/ontology/outflow>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_outflow.ttl
grep '<http://dbpedia.org/ontology/parentCompany>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_parentCompany.ttl
grep '<http://dbpedia.org/ontology/parish>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_parish.ttl
grep '<http://dbpedia.org/ontology/patron>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_patron.ttl
grep '<http://dbpedia.org/ontology/picture>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_picture.ttl
grep '<http://dbpedia.org/ontology/pictureFormat>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_pictureFormat.ttl
grep '<http://dbpedia.org/ontology/position>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_position.ttl
grep '<http://dbpedia.org/ontology/premierePlace>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_premierePlace.ttl
grep '<http://dbpedia.org/ontology/president>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_president.ttl
grep '<http://dbpedia.org/ontology/previousWork>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_previousWork.ttl
grep '<http://dbpedia.org/ontology/product>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_product.ttl
grep '<http://dbpedia.org/ontology/profession>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_profession.ttl
grep '<http://dbpedia.org/ontology/programmingLanguage>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_programmingLanguage.ttl
grep '<http://dbpedia.org/ontology/publisher>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_publisher.ttl
grep '<http://dbpedia.org/ontology/recordLabel>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_recordLabel.ttl
grep '<http://dbpedia.org/ontology/regionServed>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_regionServed.ttl
grep '<http://dbpedia.org/ontology/religion>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_religion.ttl
grep '<http://dbpedia.org/ontology/river>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_river.ttl
grep '<http://dbpedia.org/ontology/riverMouth>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_riverMouth.ttl
grep '<http://dbpedia.org/ontology/routeStart>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_routeStart.ttl
grep '<http://dbpedia.org/ontology/season>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_season.ttl
grep '<http://dbpedia.org/ontology/secondLeader>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_secondLeader.ttl
grep '<http://dbpedia.org/ontology/series>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_series.ttl
grep '<http://dbpedia.org/ontology/shuttle>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_shuttle.ttl
grep '<http://dbpedia.org/ontology/soccerTournamentTopScorer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_soccerTournamentTopScorer.ttl
grep '<http://dbpedia.org/ontology/spacecraft>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_spacecraft.ttl
grep '<http://dbpedia.org/ontology/spokenIn>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_spokenIn.ttl
grep '<http://dbpedia.org/ontology/starring>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_starring.ttl
grep '<http://dbpedia.org/ontology/state>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_state.ttl
grep '<http://dbpedia.org/ontology/successor>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_successor.ttl
grep '<http://dbpedia.org/ontology/teachingStaff>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_teachingStaff.ttl
grep '<http://dbpedia.org/ontology/tenant>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_tenant.ttl
grep '<http://dbpedia.org/ontology/thirdCommander>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_thirdCommander.ttl
grep '<http://dbpedia.org/ontology/timeZone>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_timeZone.ttl
grep '<http://dbpedia.org/ontology/trainer>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_trainer.ttl
grep '<http://dbpedia.org/ontology/translator>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_translator.ttl
grep '<http://dbpedia.org/ontology/unitaryAuthority>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_unitaryAuthority.ttl
grep '<http://dbpedia.org/ontology/winsAtMajors>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_winsAtMajors.ttl
grep '<http://dbpedia.org/ontology/youthClub>' ../resources/de//turtle/mappingbased_objects_de.ttl>>../resources/de//property/dbo_youthClub.ttl
