#!/bin/sh
grep '<http://dbpedia.org/ontology/AdministrativeRegion>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_AdministrativeRegion.ttl
grep '<http://dbpedia.org/ontology/Airline>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Airline.ttl
grep '<http://dbpedia.org/ontology/Album>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Album.ttl
grep '<http://dbpedia.org/ontology/Animal>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Animal.ttl
grep '<http://dbpedia.org/ontology/Archaea>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Archaea.ttl
grep '<http://dbpedia.org/ontology/ArchitecturalStructure>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_ArchitecturalStructure.ttl
grep '<http://dbpedia.org/ontology/Artist>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Artist.ttl
grep '<http://dbpedia.org/ontology/Astronaut>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Astronaut.ttl
grep '<http://dbpedia.org/ontology/Automobile>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Automobile.ttl
grep '<http://dbpedia.org/ontology/Bacteria>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Bacteria.ttl
grep '<http://dbpedia.org/ontology/BaseballTeam>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_BaseballTeam.ttl
grep '<http://dbpedia.org/ontology/Beverage>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Beverage.ttl
grep '<http://dbpedia.org/ontology/BodyOfWater>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_BodyOfWater.ttl
grep '<http://dbpedia.org/ontology/Bridge>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Bridge.ttl
grep '<http://dbpedia.org/ontology/BullFighter>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_BullFighter.ttl
grep '<http://dbpedia.org/ontology/CelestialBody>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_CelestialBody.ttl
grep '<http://dbpedia.org/ontology/Chef>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Chef.ttl
grep '<http://dbpedia.org/ontology/ClubMoss>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_ClubMoss.ttl
grep '<http://dbpedia.org/ontology/Colour>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Colour.ttl
grep '<http://dbpedia.org/ontology/Conifer>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Conifer.ttl
grep '<http://dbpedia.org/ontology/Criminal>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Criminal.ttl
grep '<http://dbpedia.org/ontology/Currency>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Currency.ttl
grep '<http://dbpedia.org/ontology/Cyclist>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Cyclist.ttl
grep '<http://dbpedia.org/ontology/Drug>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Drug.ttl
grep '<http://dbpedia.org/ontology/Fern>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Fern.ttl
grep '<http://dbpedia.org/ontology/Film>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Film.ttl
grep '<http://dbpedia.org/ontology/FloweringPlant>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_FloweringPlant.ttl
grep '<http://dbpedia.org/ontology/Fungus>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Fungus.ttl
grep '<http://dbpedia.org/ontology/Game>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Game.ttl
grep '<http://dbpedia.org/ontology/Gnetophytes>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Gnetophytes.ttl
grep '<http://dbpedia.org/ontology/HistoricBuilding>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_HistoricBuilding.ttl
grep '<http://dbpedia.org/ontology/Hospital>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Hospital.ttl
grep '<http://dbpedia.org/ontology/Insect>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Insect.ttl
grep '<http://dbpedia.org/ontology/Island>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Island.ttl
grep '<http://dbpedia.org/ontology/Lake>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Lake.ttl
grep '<http://dbpedia.org/ontology/Locality>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Locality.ttl
grep '<http://dbpedia.org/ontology/Mammal>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Mammal.ttl
grep '<http://dbpedia.org/ontology/MilitaryConflict>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_MilitaryConflict.ttl
grep '<http://dbpedia.org/ontology/Mineral>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Mineral.ttl
grep '<http://dbpedia.org/ontology/Mollusca>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Mollusca.ttl
grep '<http://dbpedia.org/ontology/MotorsportRacer>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_MotorsportRacer.ttl
grep '<http://dbpedia.org/ontology/Municipality>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Municipality.ttl
grep '<http://dbpedia.org/ontology/Museum>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Museum.ttl
grep '<http://dbpedia.org/ontology/MusicGenre>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_MusicGenre.ttl
grep '<http://dbpedia.org/ontology/MusicalWork>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_MusicalWork.ttl
grep '<http://dbpedia.org/ontology/Noble>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Noble.ttl
grep '<http://dbpedia.org/ontology/Olympics>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Olympics.ttl
grep '<http://dbpedia.org/ontology/Painting>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Painting.ttl
grep '<http://dbpedia.org/ontology/Person>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Person.ttl
grep '<http://dbpedia.org/ontology/Plant>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Plant.ttl
grep '<http://dbpedia.org/ontology/PoliticalParty>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_PoliticalParty.ttl
grep '<http://dbpedia.org/ontology/President>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_President.ttl
grep '<http://dbpedia.org/ontology/Protein>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Protein.ttl
grep '<http://dbpedia.org/ontology/Referee>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Referee.ttl
grep '<http://dbpedia.org/ontology/ReligiousBuilding>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_ReligiousBuilding.ttl
grep '<http://dbpedia.org/ontology/River>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_River.ttl
grep '<http://dbpedia.org/ontology/RouteOfTransportation>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_RouteOfTransportation.ttl
grep '<http://dbpedia.org/ontology/Saint>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Saint.ttl
grep '<http://dbpedia.org/ontology/Scientist>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Scientist.ttl
grep '<http://dbpedia.org/ontology/ShoppingMall>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_ShoppingMall.ttl
grep '<http://dbpedia.org/ontology/SoccerClub>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_SoccerClub.ttl
grep '<http://dbpedia.org/ontology/SoccerTournament>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_SoccerTournament.ttl
grep '<http://dbpedia.org/ontology/Song>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Song.ttl
grep '<http://dbpedia.org/ontology/Sport>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Sport.ttl
grep '<http://dbpedia.org/ontology/Station>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Station.ttl
grep '<http://dbpedia.org/ontology/TelevisionEpisode>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_TelevisionEpisode.ttl
grep '<http://dbpedia.org/ontology/TelevisionStation>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_TelevisionStation.ttl
grep '<http://dbpedia.org/ontology/Theatre>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Theatre.ttl
grep '<http://dbpedia.org/ontology/University>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_University.ttl
grep '<http://dbpedia.org/ontology/VideoGame>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_VideoGame.ttl
grep '<http://dbpedia.org/ontology/Weapon>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Weapon.ttl
grep '<http://dbpedia.org/ontology/WorldHeritageSite>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_WorldHeritageSite.ttl
grep '<http://dbpedia.org/ontology/Writer>' ../resources/es//turtle/instance_types_es.ttl>>../resources/es//entity/dbo_Writer.ttl
