#!/bin/sh
grep '<http://dbpedia.org/ontology/album>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_album.ttl
grep '<http://dbpedia.org/ontology/alpsMainPart>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_alpsMainPart.ttl
grep '<http://dbpedia.org/ontology/alpsSection>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_alpsSection.ttl
grep '<http://dbpedia.org/ontology/alpsSubsection>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_alpsSubsection.ttl
grep '<http://dbpedia.org/ontology/altitude>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_altitude.ttl
grep '<http://dbpedia.org/ontology/architecturalStyle>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_architecturalStyle.ttl
grep '<http://dbpedia.org/ontology/associatedBand>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_associatedBand.ttl
grep '<http://dbpedia.org/ontology/author>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_author.ttl
grep '<http://dbpedia.org/ontology/award>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_award.ttl
grep '<http://dbpedia.org/ontology/binomialAuthority>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_binomialAuthority.ttl
grep '<http://dbpedia.org/ontology/builder>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_builder.ttl
grep '<http://dbpedia.org/ontology/careerStation>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_careerStation.ttl
grep '<http://dbpedia.org/ontology/chiefEditor>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_chiefEditor.ttl
grep '<http://dbpedia.org/ontology/citizenship>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_citizenship.ttl
grep '<http://dbpedia.org/ontology/classis>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_classis.ttl
grep '<http://dbpedia.org/ontology/coach>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_coach.ttl
grep '<http://dbpedia.org/ontology/competitionTitle>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_competitionTitle.ttl
grep '<http://dbpedia.org/ontology/country>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_country.ttl
grep '<http://dbpedia.org/ontology/creator>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_creator.ttl
grep '<http://dbpedia.org/ontology/deathPlace>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_deathPlace.ttl
grep '<http://dbpedia.org/ontology/director>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_director.ttl
grep '<http://dbpedia.org/ontology/division>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_division.ttl
grep '<http://dbpedia.org/ontology/dubber>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_dubber.ttl
grep '<http://dbpedia.org/ontology/engineer>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_engineer.ttl
grep '<http://dbpedia.org/ontology/executiveProducer>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_executiveProducer.ttl
grep '<http://dbpedia.org/ontology/federation>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_federation.ttl
grep '<http://dbpedia.org/ontology/format>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_format.ttl
grep '<http://dbpedia.org/ontology/foundedBy>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_foundedBy.ttl
grep '<http://dbpedia.org/ontology/garrison>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_garrison.ttl
grep '<http://dbpedia.org/ontology/genre>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_genre.ttl
grep '<http://dbpedia.org/ontology/headquarter>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_headquarter.ttl
grep '<http://dbpedia.org/ontology/industry>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_industry.ttl
grep '<http://dbpedia.org/ontology/keyPerson>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_keyPerson.ttl
grep '<http://dbpedia.org/ontology/language>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_language.ttl
grep '<http://dbpedia.org/ontology/leader>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_leader.ttl
grep '<http://dbpedia.org/ontology/leaderParty>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_leaderParty.ttl
grep '<http://dbpedia.org/ontology/legalForm>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_legalForm.ttl
grep '<http://dbpedia.org/ontology/locatedInArea>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_locatedInArea.ttl
grep '<http://dbpedia.org/ontology/locationCountry>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_locationCountry.ttl
grep '<http://dbpedia.org/ontology/map>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_map.ttl
grep '<http://dbpedia.org/ontology/mediaType>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_mediaType.ttl
grep '<http://dbpedia.org/ontology/mountainRange>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_mountainRange.ttl
grep '<http://dbpedia.org/ontology/nationality>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_nationality.ttl
grep '<http://dbpedia.org/ontology/officialLanguage>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_officialLanguage.ttl
grep '<http://dbpedia.org/ontology/order>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_order.ttl
grep '<http://dbpedia.org/ontology/originalLanguage>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_originalLanguage.ttl
grep '<http://dbpedia.org/ontology/owningOrganisation>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_owningOrganisation.ttl
grep '<http://dbpedia.org/ontology/parent>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_parent.ttl
grep '<http://dbpedia.org/ontology/patron>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_patron.ttl
grep '<http://dbpedia.org/ontology/phylum>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_phylum.ttl
grep '<http://dbpedia.org/ontology/position>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_position.ttl
grep '<http://dbpedia.org/ontology/president>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_president.ttl
grep '<http://dbpedia.org/ontology/producer>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_producer.ttl
grep '<http://dbpedia.org/ontology/productionCompany>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_productionCompany.ttl
grep '<http://dbpedia.org/ontology/province>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_province.ttl
grep '<http://dbpedia.org/ontology/recordLabel>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_recordLabel.ttl
grep '<http://dbpedia.org/ontology/rector>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_rector.ttl
grep '<http://dbpedia.org/ontology/religion>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_religion.ttl
grep '<http://dbpedia.org/ontology/restingPlace>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_restingPlace.ttl
grep '<http://dbpedia.org/ontology/routeEndLocation>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_routeEndLocation.ttl
grep '<http://dbpedia.org/ontology/saint>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_saint.ttl
grep '<http://dbpedia.org/ontology/servingRailwayLine>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_servingRailwayLine.ttl
grep '<http://dbpedia.org/ontology/settlement>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_settlement.ttl
grep '<http://dbpedia.org/ontology/species>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_species.ttl
grep '<http://dbpedia.org/ontology/sportDiscipline>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_sportDiscipline.ttl
grep '<http://dbpedia.org/ontology/stadium>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_stadium.ttl
grep '<http://dbpedia.org/ontology/state>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_state.ttl
grep '<http://dbpedia.org/ontology/subsequentWork>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_subsequentWork.ttl
grep '<http://dbpedia.org/ontology/tenant>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_tenant.ttl
grep '<http://dbpedia.org/ontology/type>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_type.ttl
grep '<http://dbpedia.org/ontology/writer>' ../resources/it/turtle/it_allTriples.ttl>>../resources/it/property/dbo_writer.ttl
