#!/bin/sh
grep '<http://dbpedia.org/ontology/Agent>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Agent.ttl
grep '<http://dbpedia.org/ontology/Airline>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Airline.ttl
grep '<http://dbpedia.org/ontology/Album>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Album.ttl
grep '<http://dbpedia.org/ontology/ArchitecturalStructure>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_ArchitecturalStructure.ttl
grep '<http://dbpedia.org/ontology/Astronaut>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Astronaut.ttl
grep '<http://dbpedia.org/ontology/AthleticsPlayer>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_AthleticsPlayer.ttl
grep '<http://dbpedia.org/ontology/Automobile>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Automobile.ttl
grep '<http://dbpedia.org/ontology/Band>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Band.ttl
grep '<http://dbpedia.org/ontology/BasketballPlayer>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_BasketballPlayer.ttl
grep '<http://dbpedia.org/ontology/Biathlete>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Biathlete.ttl
grep '<http://dbpedia.org/ontology/Boxer>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Boxer.ttl
grep '<http://dbpedia.org/ontology/BrownDwarf>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_BrownDwarf.ttl
grep '<http://dbpedia.org/ontology/Canoeist>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Canoeist.ttl
grep '<http://dbpedia.org/ontology/Cave>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Cave.ttl
grep '<http://dbpedia.org/ontology/ChemicalCompound>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_ChemicalCompound.ttl
grep '<http://dbpedia.org/ontology/City>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_City.ttl
grep '<http://dbpedia.org/ontology/Country>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Country.ttl
grep '<http://dbpedia.org/ontology/Curler>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Curler.ttl
grep '<http://dbpedia.org/ontology/DTMRacer>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_DTMRacer.ttl
grep '<http://dbpedia.org/ontology/Diocese>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Diocese.ttl
grep '<http://dbpedia.org/ontology/District>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_District.ttl
grep '<http://dbpedia.org/ontology/Event>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Event.ttl
grep '<http://dbpedia.org/ontology/Film>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Film.ttl
grep '<http://dbpedia.org/ontology/FormulaOneRacer>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_FormulaOneRacer.ttl
grep '<http://dbpedia.org/ontology/Game>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Game.ttl
grep '<http://dbpedia.org/ontology/HighDiver>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_HighDiver.ttl
grep '<http://dbpedia.org/ontology/IceHockeyPlayer>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_IceHockeyPlayer.ttl
grep '<http://dbpedia.org/ontology/Lake>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Lake.ttl
grep '<http://dbpedia.org/ontology/Legislature>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Legislature.ttl
grep '<http://dbpedia.org/ontology/Lighthouse>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Lighthouse.ttl
grep '<http://dbpedia.org/ontology/LunarCrater>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_LunarCrater.ttl
grep '<http://dbpedia.org/ontology/MilitaryUnit>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_MilitaryUnit.ttl
grep '<http://dbpedia.org/ontology/Mineral>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Mineral.ttl
grep '<http://dbpedia.org/ontology/MountainRange>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_MountainRange.ttl
grep '<http://dbpedia.org/ontology/Museum>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Museum.ttl
grep '<http://dbpedia.org/ontology/Musical>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Musical.ttl
grep '<http://dbpedia.org/ontology/NordicCombined>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_NordicCombined.ttl
grep '<http://dbpedia.org/ontology/Olympics>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Olympics.ttl
grep '<http://dbpedia.org/ontology/Organisation>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Organisation.ttl
grep '<http://dbpedia.org/ontology/PeriodicalLiterature>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_PeriodicalLiterature.ttl
grep '<http://dbpedia.org/ontology/Place>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Place.ttl
grep '<http://dbpedia.org/ontology/Play>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Play.ttl
grep '<http://dbpedia.org/ontology/ProgrammingLanguage>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_ProgrammingLanguage.ttl
grep '<http://dbpedia.org/ontology/Protein>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Protein.ttl
grep '<http://dbpedia.org/ontology/PublicTransitSystem>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_PublicTransitSystem.ttl
grep '<http://dbpedia.org/ontology/RadioProgram>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_RadioProgram.ttl
grep '<http://dbpedia.org/ontology/River>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_River.ttl
grep '<http://dbpedia.org/ontology/RollerCoaster>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_RollerCoaster.ttl
grep '<http://dbpedia.org/ontology/RugbyPlayer>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_RugbyPlayer.ttl
grep '<http://dbpedia.org/ontology/Settlement>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Settlement.ttl
grep '<http://dbpedia.org/ontology/Single>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Single.ttl
grep '<http://dbpedia.org/ontology/Skier>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Skier.ttl
grep '<http://dbpedia.org/ontology/SoccerClub>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_SoccerClub.ttl
grep '<http://dbpedia.org/ontology/SoccerTournament>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_SoccerTournament.ttl
grep '<http://dbpedia.org/ontology/SpaceMission>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_SpaceMission.ttl
grep '<http://dbpedia.org/ontology/Species>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Species.ttl
grep '<http://dbpedia.org/ontology/SportsEvent>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_SportsEvent.ttl
grep '<http://dbpedia.org/ontology/Square>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Square.ttl
grep '<http://dbpedia.org/ontology/Star>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Star.ttl
grep '<http://dbpedia.org/ontology/SumoWrestler>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_SumoWrestler.ttl
grep '<http://dbpedia.org/ontology/TelevisionShow>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_TelevisionShow.ttl
grep '<http://dbpedia.org/ontology/TennisPlayer>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_TennisPlayer.ttl
grep '<http://dbpedia.org/ontology/Theatre>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Theatre.ttl
grep '<http://dbpedia.org/ontology/University>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_University.ttl
grep '<http://dbpedia.org/ontology/VolleyballPlayer>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_VolleyballPlayer.ttl
grep '<http://dbpedia.org/ontology/Website>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Website.ttl
grep '<http://dbpedia.org/ontology/WinterSportPlayer>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_WinterSportPlayer.ttl
grep '<http://dbpedia.org/ontology/Wrestler>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Wrestler.ttl
grep '<http://dbpedia.org/ontology/Zoo>' ../resources/de//turtle/instance_types_de.ttl>>../resources/de//entity/dbo_Zoo.ttl
