#!/bin/sh
grep '<http://dbpedia.org/ontology/AcademicJournal>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_AcademicJournal.ttl
grep '<http://dbpedia.org/ontology/AdministrativeRegion>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_AdministrativeRegion.ttl
grep '<http://dbpedia.org/ontology/Aircraft>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Aircraft.ttl
grep '<http://dbpedia.org/ontology/Airport>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Airport.ttl
grep '<http://dbpedia.org/ontology/AmateurBoxer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_AmateurBoxer.ttl
grep '<http://dbpedia.org/ontology/AmericanFootballLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_AmericanFootballLeague.ttl
grep '<http://dbpedia.org/ontology/AmericanFootballTeam>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_AmericanFootballTeam.ttl
grep '<http://dbpedia.org/ontology/AmusementParkAttraction>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_AmusementParkAttraction.ttl
grep '<http://dbpedia.org/ontology/Animal>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Animal.ttl
grep '<http://dbpedia.org/ontology/Anime>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Anime.ttl
grep '<http://dbpedia.org/ontology/Archaea>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Archaea.ttl
grep '<http://dbpedia.org/ontology/ArchitecturalStructure>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ArchitecturalStructure.ttl
grep '<http://dbpedia.org/ontology/ArtificialSatellite>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ArtificialSatellite.ttl
grep '<http://dbpedia.org/ontology/ArtistDiscography>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ArtistDiscography.ttl
grep '<http://dbpedia.org/ontology/Asteroid>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Asteroid.ttl
grep '<http://dbpedia.org/ontology/Athlete>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Athlete.ttl
grep '<http://dbpedia.org/ontology/AustralianFootballTeam>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_AustralianFootballTeam.ttl
grep '<http://dbpedia.org/ontology/AutoRacingLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_AutoRacingLeague.ttl
grep '<http://dbpedia.org/ontology/AutomobileEngine>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_AutomobileEngine.ttl
grep '<http://dbpedia.org/ontology/Bacteria>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Bacteria.ttl
grep '<http://dbpedia.org/ontology/Band>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Band.ttl
grep '<http://dbpedia.org/ontology/Baronet>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Baronet.ttl
grep '<http://dbpedia.org/ontology/BaseballPlayer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_BaseballPlayer.ttl
grep '<http://dbpedia.org/ontology/BaseballTeam>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_BaseballTeam.ttl
grep '<http://dbpedia.org/ontology/BasketballPlayer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_BasketballPlayer.ttl
grep '<http://dbpedia.org/ontology/Bay>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Bay.ttl
grep '<http://dbpedia.org/ontology/BeautyQueen>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_BeautyQueen.ttl
grep '<http://dbpedia.org/ontology/BiologicalDatabase>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_BiologicalDatabase.ttl
grep '<http://dbpedia.org/ontology/BodyOfWater>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_BodyOfWater.ttl
grep '<http://dbpedia.org/ontology/Bone>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Bone.ttl
grep '<http://dbpedia.org/ontology/BowlingLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_BowlingLeague.ttl
grep '<http://dbpedia.org/ontology/BoxingLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_BoxingLeague.ttl
grep '<http://dbpedia.org/ontology/Brewery>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Brewery.ttl
grep '<http://dbpedia.org/ontology/BroadcastNetwork>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_BroadcastNetwork.ttl
grep '<http://dbpedia.org/ontology/BusCompany>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_BusCompany.ttl
grep '<http://dbpedia.org/ontology/CanadianFootballLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_CanadianFootballLeague.ttl
grep '<http://dbpedia.org/ontology/Canal>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Canal.ttl
grep '<http://dbpedia.org/ontology/Cardinal>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Cardinal.ttl
grep '<http://dbpedia.org/ontology/Cave>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Cave.ttl
grep '<http://dbpedia.org/ontology/Cheese>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Cheese.ttl
grep '<http://dbpedia.org/ontology/ChemicalCompound>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ChemicalCompound.ttl
grep '<http://dbpedia.org/ontology/ChristianBishop>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ChristianBishop.ttl
grep '<http://dbpedia.org/ontology/ClassicalMusicArtist>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ClassicalMusicArtist.ttl
grep '<http://dbpedia.org/ontology/Cleric>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Cleric.ttl
grep '<http://dbpedia.org/ontology/College>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_College.ttl
grep '<http://dbpedia.org/ontology/Colour>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Colour.ttl
grep '<http://dbpedia.org/ontology/ComedyGroup>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ComedyGroup.ttl
grep '<http://dbpedia.org/ontology/ComicStrip>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ComicStrip.ttl
grep '<http://dbpedia.org/ontology/ComicsCreator>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ComicsCreator.ttl
grep '<http://dbpedia.org/ontology/ConcentrationCamp>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ConcentrationCamp.ttl
grep '<http://dbpedia.org/ontology/Conifer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Conifer.ttl
grep '<http://dbpedia.org/ontology/Continent>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Continent.ttl
grep '<http://dbpedia.org/ontology/Country>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Country.ttl
grep '<http://dbpedia.org/ontology/CricketGround>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_CricketGround.ttl
grep '<http://dbpedia.org/ontology/CricketTeam>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_CricketTeam.ttl
grep '<http://dbpedia.org/ontology/Criminal>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Criminal.ttl
grep '<http://dbpedia.org/ontology/CultivatedVariety>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_CultivatedVariety.ttl
grep '<http://dbpedia.org/ontology/CurlingLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_CurlingLeague.ttl
grep '<http://dbpedia.org/ontology/Cycad>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Cycad.ttl
grep '<http://dbpedia.org/ontology/CyclingTeam>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_CyclingTeam.ttl
grep '<http://dbpedia.org/ontology/Dam>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Dam.ttl
grep '<http://dbpedia.org/ontology/Device>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Device.ttl
grep '<http://dbpedia.org/ontology/Disease>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Disease.ttl
grep '<http://dbpedia.org/ontology/Earthquake>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Earthquake.ttl
grep '<http://dbpedia.org/ontology/EducationalInstitution>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_EducationalInstitution.ttl
grep '<http://dbpedia.org/ontology/Embryology>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Embryology.ttl
grep '<http://dbpedia.org/ontology/Entomologist>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Entomologist.ttl
grep '<http://dbpedia.org/ontology/EthnicGroup>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_EthnicGroup.ttl
grep '<http://dbpedia.org/ontology/EurovisionSongContestEntry>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_EurovisionSongContestEntry.ttl
grep '<http://dbpedia.org/ontology/Fashion>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Fashion.ttl
grep '<http://dbpedia.org/ontology/Fern>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Fern.ttl
grep '<http://dbpedia.org/ontology/FieldHockeyLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_FieldHockeyLeague.ttl
grep '<http://dbpedia.org/ontology/Film>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Film.ttl
grep '<http://dbpedia.org/ontology/Fish>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Fish.ttl
grep '<http://dbpedia.org/ontology/Food>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Food.ttl
grep '<http://dbpedia.org/ontology/FootballMatch>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_FootballMatch.ttl
grep '<http://dbpedia.org/ontology/FormulaOneTeam>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_FormulaOneTeam.ttl
grep '<http://dbpedia.org/ontology/GaelicGamesPlayer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_GaelicGamesPlayer.ttl
grep '<http://dbpedia.org/ontology/Game>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Game.ttl
grep '<http://dbpedia.org/ontology/Ginkgo>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Ginkgo.ttl
grep '<http://dbpedia.org/ontology/Glacier>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Glacier.ttl
grep '<http://dbpedia.org/ontology/GolfCourse>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_GolfCourse.ttl
grep '<http://dbpedia.org/ontology/GolfPlayer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_GolfPlayer.ttl
grep '<http://dbpedia.org/ontology/GovernmentAgency>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_GovernmentAgency.ttl
grep '<http://dbpedia.org/ontology/GrandPrix>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_GrandPrix.ttl
grep '<http://dbpedia.org/ontology/GreenAlga>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_GreenAlga.ttl
grep '<http://dbpedia.org/ontology/Guitarist>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Guitarist.ttl
grep '<http://dbpedia.org/ontology/HandballLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_HandballLeague.ttl
grep '<http://dbpedia.org/ontology/HandballTeam>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_HandballTeam.ttl
grep '<http://dbpedia.org/ontology/HistoricBuilding>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_HistoricBuilding.ttl
grep '<http://dbpedia.org/ontology/HockeyTeam>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_HockeyTeam.ttl
grep '<http://dbpedia.org/ontology/HollywoodCartoon>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_HollywoodCartoon.ttl
grep '<http://dbpedia.org/ontology/HorseRider>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_HorseRider.ttl
grep '<http://dbpedia.org/ontology/Hospital>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Hospital.ttl
grep '<http://dbpedia.org/ontology/HumanGene>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_HumanGene.ttl
grep '<http://dbpedia.org/ontology/IceHockeyPlayer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_IceHockeyPlayer.ttl
grep '<http://dbpedia.org/ontology/InlineHockeyLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_InlineHockeyLeague.ttl
grep '<http://dbpedia.org/ontology/Island>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Island.ttl
grep '<http://dbpedia.org/ontology/Journalist>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Journalist.ttl
grep '<http://dbpedia.org/ontology/LacrosseLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_LacrosseLeague.ttl
grep '<http://dbpedia.org/ontology/Lake>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Lake.ttl
grep '<http://dbpedia.org/ontology/LaunchPad>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_LaunchPad.ttl
grep '<http://dbpedia.org/ontology/Legislature>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Legislature.ttl
grep '<http://dbpedia.org/ontology/Ligament>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Ligament.ttl
grep '<http://dbpedia.org/ontology/Locomotive>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Locomotive.ttl
grep '<http://dbpedia.org/ontology/Magazine>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Magazine.ttl
grep '<http://dbpedia.org/ontology/Manga>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Manga.ttl
grep '<http://dbpedia.org/ontology/Mayor>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Mayor.ttl
grep '<http://dbpedia.org/ontology/MemberOfParliament>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_MemberOfParliament.ttl
grep '<http://dbpedia.org/ontology/MilitaryPerson>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_MilitaryPerson.ttl
grep '<http://dbpedia.org/ontology/MilitaryUnit>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_MilitaryUnit.ttl
grep '<http://dbpedia.org/ontology/MixedMartialArtsEvent>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_MixedMartialArtsEvent.ttl
grep '<http://dbpedia.org/ontology/Model>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Model.ttl
grep '<http://dbpedia.org/ontology/Monarch>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Monarch.ttl
grep '<http://dbpedia.org/ontology/Moss>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Moss.ttl
grep '<http://dbpedia.org/ontology/MotorcycleRacingLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_MotorcycleRacingLeague.ttl
grep '<http://dbpedia.org/ontology/MotorsportSeason>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_MotorsportSeason.ttl
grep '<http://dbpedia.org/ontology/MountainPass>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_MountainPass.ttl
grep '<http://dbpedia.org/ontology/Murderer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Murderer.ttl
grep '<http://dbpedia.org/ontology/Museum>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Museum.ttl
grep '<http://dbpedia.org/ontology/MusicGenre>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_MusicGenre.ttl
grep '<http://dbpedia.org/ontology/MusicalArtist>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_MusicalArtist.ttl
grep '<http://dbpedia.org/ontology/MythologicalFigure>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_MythologicalFigure.ttl
grep '<http://dbpedia.org/ontology/NascarDriver>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_NascarDriver.ttl
grep '<http://dbpedia.org/ontology/NationalFootballLeagueEvent>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_NationalFootballLeagueEvent.ttl
grep '<http://dbpedia.org/ontology/Nerve>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Nerve.ttl
grep '<http://dbpedia.org/ontology/Newspaper>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Newspaper.ttl
grep '<http://dbpedia.org/ontology/Non-ProfitOrganisation>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Non-ProfitOrganisation.ttl
grep '<http://dbpedia.org/ontology/OfficeHolder>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_OfficeHolder.ttl
grep '<http://dbpedia.org/ontology/OlympicResult>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_OlympicResult.ttl
grep '<http://dbpedia.org/ontology/Organisation>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Organisation.ttl
grep '<http://dbpedia.org/ontology/Park>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Park.ttl
grep '<http://dbpedia.org/ontology/Philosopher>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Philosopher.ttl
grep '<http://dbpedia.org/ontology/Place>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Place.ttl
grep '<http://dbpedia.org/ontology/Plant>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Plant.ttl
grep '<http://dbpedia.org/ontology/PlayboyPlaymate>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_PlayboyPlaymate.ttl
grep '<http://dbpedia.org/ontology/Poet>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Poet.ttl
grep '<http://dbpedia.org/ontology/PoliticalParty>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_PoliticalParty.ttl
grep '<http://dbpedia.org/ontology/PoloLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_PoloLeague.ttl
grep '<http://dbpedia.org/ontology/PowerStation>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_PowerStation.ttl
grep '<http://dbpedia.org/ontology/President>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_President.ttl
grep '<http://dbpedia.org/ontology/Prison>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Prison.ttl
grep '<http://dbpedia.org/ontology/ProtectedArea>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ProtectedArea.ttl
grep '<http://dbpedia.org/ontology/PublicTransitSystem>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_PublicTransitSystem.ttl
grep '<http://dbpedia.org/ontology/RaceHorse>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_RaceHorse.ttl
grep '<http://dbpedia.org/ontology/RacingDriver>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_RacingDriver.ttl
grep '<http://dbpedia.org/ontology/RadioProgram>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_RadioProgram.ttl
grep '<http://dbpedia.org/ontology/RailwayLine>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_RailwayLine.ttl
grep '<http://dbpedia.org/ontology/RailwayTunnel>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_RailwayTunnel.ttl
grep '<http://dbpedia.org/ontology/Religious>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Religious.ttl
grep '<http://dbpedia.org/ontology/Reptile>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Reptile.ttl
grep '<http://dbpedia.org/ontology/Restaurant>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Restaurant.ttl
grep '<http://dbpedia.org/ontology/Road>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Road.ttl
grep '<http://dbpedia.org/ontology/RoadTunnel>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_RoadTunnel.ttl
grep '<http://dbpedia.org/ontology/RollerCoaster>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_RollerCoaster.ttl
grep '<http://dbpedia.org/ontology/Royalty>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Royalty.ttl
grep '<http://dbpedia.org/ontology/RugbyLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_RugbyLeague.ttl
grep '<http://dbpedia.org/ontology/Saint>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Saint.ttl
grep '<http://dbpedia.org/ontology/Scientist>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Scientist.ttl
grep '<http://dbpedia.org/ontology/Sea>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Sea.ttl
grep '<http://dbpedia.org/ontology/Settlement>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Settlement.ttl
grep '<http://dbpedia.org/ontology/ShoppingMall>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_ShoppingMall.ttl
grep '<http://dbpedia.org/ontology/SiteOfSpecialScientificInterest>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SiteOfSpecialScientificInterest.ttl
grep '<http://dbpedia.org/ontology/SkiArea>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SkiArea.ttl
grep '<http://dbpedia.org/ontology/Skyscraper>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Skyscraper.ttl
grep '<http://dbpedia.org/ontology/SnookerPlayer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SnookerPlayer.ttl
grep '<http://dbpedia.org/ontology/SoapCharacter>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SoapCharacter.ttl
grep '<http://dbpedia.org/ontology/SoccerClubSeason>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SoccerClubSeason.ttl
grep '<http://dbpedia.org/ontology/SoccerManager>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SoccerManager.ttl
grep '<http://dbpedia.org/ontology/SoccerTournament>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SoccerTournament.ttl
grep '<http://dbpedia.org/ontology/Software>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Software.ttl
grep '<http://dbpedia.org/ontology/Song>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Song.ttl
grep '<http://dbpedia.org/ontology/SpaceStation>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SpaceStation.ttl
grep '<http://dbpedia.org/ontology/Species>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Species.ttl
grep '<http://dbpedia.org/ontology/SpeedwayRider>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SpeedwayRider.ttl
grep '<http://dbpedia.org/ontology/Sport>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Sport.ttl
grep '<http://dbpedia.org/ontology/SportsLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SportsLeague.ttl
grep '<http://dbpedia.org/ontology/SportsTeamMember>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SportsTeamMember.ttl
grep '<http://dbpedia.org/ontology/Stadium>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Stadium.ttl
grep '<http://dbpedia.org/ontology/Station>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Station.ttl
grep '<http://dbpedia.org/ontology/SumoWrestler>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_SumoWrestler.ttl
grep '<http://dbpedia.org/ontology/Surname>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Surname.ttl
grep '<http://dbpedia.org/ontology/TableTennisPlayer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_TableTennisPlayer.ttl
grep '<http://dbpedia.org/ontology/TelevisionHost>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_TelevisionHost.ttl
grep '<http://dbpedia.org/ontology/TelevisionShow>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_TelevisionShow.ttl
grep '<http://dbpedia.org/ontology/TennisLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_TennisLeague.ttl
grep '<http://dbpedia.org/ontology/TennisTournament>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_TennisTournament.ttl
grep '<http://dbpedia.org/ontology/Town>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Town.ttl
grep '<http://dbpedia.org/ontology/Train>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Train.ttl
grep '<http://dbpedia.org/ontology/University>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_University.ttl
grep '<http://dbpedia.org/ontology/Vein>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Vein.ttl
grep '<http://dbpedia.org/ontology/VideoGame>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_VideoGame.ttl
grep '<http://dbpedia.org/ontology/Village>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Village.ttl
grep '<http://dbpedia.org/ontology/Volcano>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Volcano.ttl
grep '<http://dbpedia.org/ontology/VolleyballLeague>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_VolleyballLeague.ttl
grep '<http://dbpedia.org/ontology/WaterRide>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_WaterRide.ttl
grep '<http://dbpedia.org/ontology/Weapon>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Weapon.ttl
grep '<http://dbpedia.org/ontology/WineRegion>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_WineRegion.ttl
grep '<http://dbpedia.org/ontology/WomensTennisAssociationTournament>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_WomensTennisAssociationTournament.ttl
grep '<http://dbpedia.org/ontology/Wrestler>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Wrestler.ttl
grep '<http://dbpedia.org/ontology/Writer>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Writer.ttl
grep '<http://dbpedia.org/ontology/Year>' ../resources/en//turtle/instance_types_en.ttl>>../resources/en//entity/dbo_Year.ttl
