#!/bin/sh
grep '<http://dbpedia.org/ontology/leader>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_leader.ttl
grep '<http://dbpedia.org/ontology/alterEgo>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_alterEgo.ttl
grep '<http://dbpedia.org/ontology/author>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_author.ttl
grep '<http://dbpedia.org/ontology/literaryGenre>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_literaryGenre.ttl
grep '<http://dbpedia.org/ontology/birthPlace>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_birthPlace.ttl
grep '<http://dbpedia.org/ontology/governmentType>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_governmentType.ttl
grep '<http://dbpedia.org/ontology/deathCause>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_deathCause.ttl
grep '<http://dbpedia.org/ontology/coach>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_coach.ttl
grep '<http://dbpedia.org/ontology/completionDate>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_completionDate.ttl
grep '<http://dbpedia.org/ontology/creator>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_creator.ttl
grep '<http://dbpedia.org/ontology/currency>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_currency.ttl
grep '<http://dbpedia.org/ontology/deathPlace>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_deathPlace.ttl
grep '<http://dbpedia.org/ontology/developer>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_developer.ttl
grep '<http://dbpedia.org/ontology/dissolutionDate>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_dissolutionDate.ttl
grep '<http://dbpedia.org/ontology/editor>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/editor.ttl
grep '<http://dbpedia.org/ontology/father>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_father.ttl
grep '<http://dbpedia.org/ontology/formOfGovernment>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_formOfGovernment.ttl
grep '<http://dbpedia.org/ontology/foundedBy>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_foundedBy.ttl
grep '<http://dbpedia.org/ontology/publisher>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_publisher.ttl
grep '<http://dbpedia.org/ontology/location>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_location.ttl
grep '<http://dbpedia.org/ontology/ground>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_ground.ttl
grep '<http://dbpedia.org/ontology/largestCity>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_largestCity.ttl
grep '<http://dbpedia.org/ontology/connotation>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_connotation.ttl
grep '<http://dbpedia.org/ontology/musicComposer>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_musicComposer.ttl
grep '<http://dbpedia.org/ontology/numberOfPages>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_numberOfPages.ttl
grep '<http://dbpedia.org/ontology/parent>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_parent.ttl
grep '<http://dbpedia.org/ontology/party>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_party.ttl
grep '<http://dbpedia.org/ontology/populationTotal>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_populationTotal.ttl
grep '<http://dbpedia.org/ontology/RecordLabel>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_RecordLabel.ttl
grep '<http://dbpedia.org/ontology/residence>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_residence.ttl
grep '<http://dbpedia.org/ontology/league>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_league.ttl
grep '<http://dbpedia.org/ontology/spouse>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_spouse.ttl
grep '<http://dbpedia.org/ontology/wineRegion>' ../resources/en//turtle/mappingbased_literals_en.ttl>>../resources/en//entity/dbo_wineRegion.ttl
