#!/bin/sh
grep '<http://dbpedia.org/ontology/Aircraft>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Aircraft.ttl
grep '<http://dbpedia.org/ontology/Album>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Album.ttl
grep '<http://dbpedia.org/ontology/Artwork>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Artwork.ttl
grep '<http://dbpedia.org/ontology/Athlete>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Athlete.ttl
grep '<http://dbpedia.org/ontology/Automobile>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Automobile.ttl
grep '<http://dbpedia.org/ontology/BasketballPlayer>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_BasketballPlayer.ttl
grep '<http://dbpedia.org/ontology/Beer>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Beer.ttl
grep '<http://dbpedia.org/ontology/Book>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Book.ttl
grep '<http://dbpedia.org/ontology/Building>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Building.ttl
grep '<http://dbpedia.org/ontology/CelestialBody>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_CelestialBody.ttl
grep '<http://dbpedia.org/ontology/ChristianBishop>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_ChristianBishop.ttl
grep '<http://dbpedia.org/ontology/Country>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Country.ttl
grep '<http://dbpedia.org/ontology/CyclingCompetition>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_CyclingCompetition.ttl
grep '<http://dbpedia.org/ontology/Dam>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Dam.ttl
grep '<http://dbpedia.org/ontology/Diocese>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Diocese.ttl
grep '<http://dbpedia.org/ontology/Dog>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Dog.ttl
grep '<http://dbpedia.org/ontology/EthnicGroup>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_EthnicGroup.ttl
grep '<http://dbpedia.org/ontology/Fencer>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Fencer.ttl
grep '<http://dbpedia.org/ontology/Film>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Film.ttl
grep '<http://dbpedia.org/ontology/Guitar>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Guitar.ttl
grep '<http://dbpedia.org/ontology/Hospital>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Hospital.ttl
grep '<http://dbpedia.org/ontology/Island>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Island.ttl
grep '<http://dbpedia.org/ontology/Legislature>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Legislature.ttl
grep '<http://dbpedia.org/ontology/Lighthouse>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Lighthouse.ttl
grep '<http://dbpedia.org/ontology/MetroStation>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_MetroStation.ttl
grep '<http://dbpedia.org/ontology/MilitaryPerson>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_MilitaryPerson.ttl
grep '<http://dbpedia.org/ontology/Mineral>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Mineral.ttl
grep '<http://dbpedia.org/ontology/MotorcycleRider>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_MotorcycleRider.ttl
grep '<http://dbpedia.org/ontology/Museum>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Museum.ttl
grep '<http://dbpedia.org/ontology/MusicGenre>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_MusicGenre.ttl
grep '<http://dbpedia.org/ontology/NaturalEvent>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_NaturalEvent.ttl
grep '<http://dbpedia.org/ontology/Newspaper>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Newspaper.ttl
grep '<http://dbpedia.org/ontology/Organisation>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Organisation.ttl
grep '<http://dbpedia.org/ontology/Politician>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Politician.ttl
grep '<http://dbpedia.org/ontology/Protein>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Protein.ttl
grep '<http://dbpedia.org/ontology/RailwayStation>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_RailwayStation.ttl
grep '<http://dbpedia.org/ontology/ReligiousBuilding>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_ReligiousBuilding.ttl
grep '<http://dbpedia.org/ontology/Road>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Road.ttl
grep '<http://dbpedia.org/ontology/Saint>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Saint.ttl
grep '<http://dbpedia.org/ontology/Ship>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Ship.ttl
grep '<http://dbpedia.org/ontology/SoccerClub>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_SoccerClub.ttl
grep '<http://dbpedia.org/ontology/SoccerPlayer>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_SoccerPlayer.ttl
grep '<http://dbpedia.org/ontology/Software>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Software.ttl
grep '<http://dbpedia.org/ontology/Species>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Species.ttl
grep '<http://dbpedia.org/ontology/SportFacility>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_SportFacility.ttl
grep '<http://dbpedia.org/ontology/SportsLeague>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_SportsLeague.ttl
grep '<http://dbpedia.org/ontology/SportsTeam>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_SportsTeam.ttl
grep '<http://dbpedia.org/ontology/Swimmer>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Swimmer.ttl
grep '<http://dbpedia.org/ontology/TelevisionShow>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_TelevisionShow.ttl
grep '<http://dbpedia.org/ontology/TennisTournament>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_TennisTournament.ttl
grep '<http://dbpedia.org/ontology/University>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_University.ttl
grep '<http://dbpedia.org/ontology/VolleyballPlayer>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_VolleyballPlayer.ttl
grep '<http://dbpedia.org/ontology/Wine>' ../resources/it//turtle/instance_types_it.ttl>>../resources/it//entity/dbo_Wine.ttl
